### ISSUE TITLE
AUTH0_ALLOW_DELETE doesn't seem to be working?

### ISSUE THREAD

**Issue by abd3** [auth0/auth0-deploy-cli#105]
Maybe I'm missing something basic, but if I use the directory-style export, add a few bogus files to my tenant configuration, and then run the auth0 dump programmatically, I don't see the bogus files being deleted.

I'm setting `'AUTH0_ALLOW_DELETE': true` in my config file and using Node.js programmatically to run the dump.

Am I missing something?

**Comment by zxan1285** [comment]
Hi. `AUTH0 ALLOW DELETE` has no effect on `dump`, it's only for `deploy`. If enabled, tool will remove any existing connections/clients/resource servers that aren't present in the source (yaml/directory).

**Comment by abd3** [comment]
OK, thanks for the clarification.
We ended up just coding in a 'rm -rf' on our tenant data to delete that so
we can pull down a fresh dump. I'm building some automated backups.
