### ISSUE TITLE
On error, doesn't exit with status 1

### ISSUE THREAD

**Issue by JasonThomasData** [auth0/auth0-deploy-cli#106]
When script errors it exits with 0 still and this affects our pipeline.

For example, when my `config.json` file has an incorrect `client_secret`, the CLI throws:

`
2019-03-14T01:58:06.654Z - error: Problem running command import
2019-03-14T01:58:06.655Z - error:  error=access_denied, error_description=Unauthorized
(node:9295) UnhandledPromiseRejectionWarning: TypeError: msg.includes is not a function
    at run.then.catch.error (/usr/local/lib/node_modules/auth0-deploy-cli/lib/index.js:83:13)
(node:9295) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9295) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

The message says this will in future return non-zero exit code... is that coming soon? If this is dependent on Node upgrading, then could you upgrade the CLI behave as expected?

**Comment by fyockm** [comment]
duplicate of #2

**Comment by JasonThomasData** [comment]
That's fine, will close, thanks
