### ISSUE TITLE
Add support for creating Hooks

### ISSUE THREAD

**Issue by sgmeyer** [auth0/auth0-deploy-cli#11]
Can this add support for creating hooks?  Today hooks can be deployed via the Webtask API or utilizing the `wt-cli` or the `Auth0 CLI` that is in beta and ships with `wt-cli` via npm.

**Comment by ncknuna** [comment]
@shawnmclean I see this was closed, but I don't see "Hooks" as part of the "Supported Features" in the README, nor do I see any comment messages recently which seem to imply that support has been added. Would you mind commenting on the current situation?
