### ISSUE TITLE
Broken auth0-source-control-extension-tools dependency

### ISSUE THREAD

**Issue by zinosama** [auth0/auth0-deploy-cli#113]
auth0-source-control-extension-tools version 3.4.0 breaks backup (export) for my private tenant. Since this dependency is [only fixed on major version](https://github.com/auth0/auth0-deploy-cli/blob/v3.1.2/package.json#L32), my cli installation at v3.1.2 automatically fetches the extension dependency at 3.4.0.

I'm not sure what's the relationship between this library and the extention library. But perhaps we can be a little more careful with this dependency by checking in the minor version?

```
2019-04-25T01:15:46.683Z - error: Problem running command export during stage load when processing type roles
2019-04-25T01:15:46.683Z - error: Cannot read property 'getAll' of undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
...
```

**Comment by fyockm** [comment]
Fixed by #118
