### ISSUE TITLE
read:roles should be added to the README.md 'scopes' section

### ISSUE THREAD

**Issue by joe-tillotson** [auth0/auth0-deploy-cli#114]
Small but important: as of (at least) version 3.3.0, the scope "read:roles" must be assigned to the auth0-deploy-cli application (for access to the Auth0 management API) or an error will be returned when running an import against an Auth0 tenant.  This scope is not mentioned in the 'scopes' section of the main README, where instructions are being provided for manually setting up the deploy client (app).

**Comment by fyockm** [comment]
@joe-tillotson you're right! would you mind submitting a PR to add?

**Comment by joe-tillotson** [comment]
Sure I'll do that.
