### ISSUE TITLE
403 “Service not enabled within domain” when including AUTH0_CLIENT_ID/SECRET credentials

### ISSUE THREAD

**Issue by abd3** [auth0/auth0-deploy-cli#116]
I'm using the Auth0 CLI to deploy configuration to a tenant. I got this working successfully on my local machine, but couldn't get it to work in a CI system despite trying many workarounds. I kept encountering the error 403 "Service not enabled within domain". There are 2 related issues: [403 error on custom domains](https://community.auth0.com/t/unable-to-authorized-with-the-custom-domain/10020) and [403 error from trailing slash](https://community.auth0.com/t/getting-service-not-enabled-within-domain-when-requesting-an-api-token/12634) but neither of those fit my situation.

I'm using a config file like this to connect to my tenant:

```
  mytenant_stage: {
    'AUTH0_DOMAIN': 'mytenant-stage.auth0.com',
    'AUTH0_CLIENT_ID': '##mytenant_stage__ID##',
    'AUTH0_CLIENT_SECRET': '##mytenant_stage__SECRET##',
    'AUTH0_KEYWORD_REPLACE_MAPPINGS': {
      'AUTH0_TENANT_NAME': 'mytenant-stage.auth0.com'
    },
    'AUTH0_ALLOW_DELETE': true,
    'AUTH0_EXCLUDED_RULES': ['rule-1-name']
  }
```

I isolated the problem and found a workaround. 

The issue turned out to be with the environment variables I was using to store CLI login credentials. I had set the client ID and secret for different environments on both my local machine and on the CI server. But I discovered a difference. On the CI server I had also set the standard environment variables AUTH0_CLIENT_ID and AUTH0_CLIENT_SECRET and they pointed to a different tenant. Apparently what happens is that the CLI uses those credentials to get the initial access token, but then attempts to use that access token to connect to my target tenant. That connection gives a 403 Forbidden error.

The workaround was to remove the AUTH0_CLIENT_… variables. Then Auth0 used the credentials for my target tenant to get the token and then to use it.
I was happy to find the workaround, but this definitely feels like a bug so I wanted to report it for investigation here.

**Comment by willvedd** [comment]
@abd3 Thanks for opening this ticket and sorry for taking so long to respond.

As you've discovered, the deploy CLI ingests all environment variables by default. In the case of a collision between configuration you have in your JSON file and environment variables, which is a common situation for multi-tenant devs, there can be unexpected results.

I've recently released a patch that prohibits environment variable inheritance by appending `--env=false` to your commands. That would ensure that only your JSON configuration file is getting read and deleting the colliding environment variables wouldn't be necessary. 

Sorry again for the delayed response, but I'm hoping this tip helps other folks!
