### ISSUE TITLE
Unable to create resourceServer with RBAC enabled 

### ISSUE THREAD

**Issue by stevezau** [auth0/auth0-deploy-cli#117]
Unable to create resourceServer with RBAC enabled.

Create resource server with the below to enable 
```
token_dialect: access_token_authz
```

```
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "Payload validation error: 'Additional properties not allowed: token_dialect'.",
  "errorCode": "invalid_body"
}
```

It appears the mgmt api does not support setting on create, only update. Logging a bug with iam-authz

**Comment by willvedd** [comment]
@stevezau Do you have a resolution on this?This strikes me as being an issue on the API-side rather than with this utility directly.

**Comment by willvedd** [comment]
Looks like an API issue; the resolution should be to omit the `token_dialect` property from the configuration. I'm opting to close this because I don't think there's anything actionable here from the Deploy CLI perspective. Please re-open if you or anyone else is still incurring this issue!
