### ISSUE TITLE
Let connections use the name or id

### ISSUE THREAD

**Issue by jennparise** [auth0/auth0-deploy-cli#120]
This code:  
` // Convert enabled_clients from id to name
  connections.forEach((connection) => {
    const dumpedConnection = {
      ...connection,
      enabled_clients: [
        ...(connection.enabled_clients || []).map((clientId) => {
          const found = clients.find(c => c.client_id === clientId);
          if (found) return found.name;
          return clientId;
        })
      ]
    };`
Converts an id to a name but we actually want to promote through environments and they won't have the same id but will have the same name. It would help us tremendously if there were a check for numbers or not and let both ids or names through.

**Comment by shawnmclean** [comment]
Hi @jennparise, could you tell us a bit more about your promotion process and how you're using the tool to do that?

**Comment by jennparise** [comment]
I don't know what we had done wrong but it used to tell us it was an invalid id when we used client name instead of id but now it is working with the name so I will close this.
