### ISSUE TITLE
Replace keywords on export

### ISSUE THREAD

**Issue by Floppy** [auth0/auth0-deploy-cli#125]
It would be super useful, especially when trying to make sure different tenants are kept in sync, to reverse the keyword replacements on export. It would never be foolproof if someone specifies an overly broad keyword, but it would be a useful feature, certainly for me!

I imagine that:

```json
{
  "example_key": "abc123"
}
```

when exported with a config file including:

```json
{
  "AUTH0_KEYWORD_REPLACE_MAPPINGS": {
    "SEKRIT_KEY": "abc123"
  }
}
```
Would become:

```json
{
  "example_key": "##SEKRIT_KEY##"
}
```

**Comment by willvedd** [comment]
Thanks for opening this, I can see how this would lead to some frustration. It's something that we are going to look at closer. However, I'm opting to close this issue as it's a duplicate with #328 and there is a bit more of a discussion there.
