### ISSUE TITLE
No newline at end of file for exports

### ISSUE THREAD

**Issue by l8nite** [auth0/auth0-deploy-cli#128]
It'd be nice if the exported files contained the trailing newline, just to avoid spurious diffs.

**Comment by sobil** [comment]
I too am bugged by this so have raised a PR to hopefully resolve it. #262

**Comment by sobil** [comment]
This should be resolved on the above PR.

**Comment by willvedd** [comment]
@sobil thanks for contributing #262! I'm going to mark this issue as closed.
