### ISSUE TITLE
Unable to change API identifier on `import`

### ISSUE THREAD

**Issue by l8nite** [auth0/auth0-deploy-cli#129]
We recently had a commit which needed to change the identifier for a resource server. The `import` command runs and says it completed successfully, but the identifier did not change in the dashboard. 

If this is expected/unsupported, perhaps the `import` process should error or warn on the situation.

The workaround for us was to delete the API and then the import was able to re-create it.

**Comment by willvedd** [comment]
@l8nite are you able to confirm wether or not this is still an active issue? It appears that a fix for this may have been merged shortly after you opened this ticket.

**Comment by sguth-affirm** [comment]
I can verify tomorrow when I’m at work - glad to see you’ve been active in this repo today :)
