### ISSUE TITLE
Add support to programmatically export to a yaml file

### ISSUE THREAD

**Issue by alpap** [auth0/auth0-deploy-cli#130]
Currently there is an option to import to yaml programmatically but there is no way to export to a yaml file programmatically

**Comment by longhungn** [comment]
There is actually an undocumented way to export to yaml programatically
```javascript
dump({
  output_folder: /path/to/output/folder,
  config: config,
  format: 'yaml', //the key is this option
})
  .then(() => console.log('Dump successful'))
  .catch(err => {
    console.log('Dump failed');
    console.log(err);
  });

```
which would be equivalent to 
`a0deploy export -c your-config-file.json -f yaml -o /path/to/output/folder` 

It would be nice if the [document](https://auth0.com/docs/extensions/deploy-cli/guides/call-deploy-cli-programmatically) is updated to reflect this
