### ISSUE TITLE
error: Problem running command export during stage load when processing type roles

### ISSUE THREAD

**Issue by bpogrebi** [auth0/auth0-deploy-cli#131]
Getting error during export with folder option: 
error: Problem running command export during stage load when processing type roles
error: {"statusCode":501,"error":"Not Implemented","message":"This feature is not enabled for this tenant."}
Can't find any options related to Roles in Tenant settings of our appliance.

Looks like this issue started with version 3.3. Downgrade to 3.2.1 resolved it.

**Comment by ShayMe21** [comment]
Support for RBAC was added recently in https://github.com/auth0/auth0-deploy-cli/pull/112
It's possible that your tenant may not have this feature enabled yet, specially if you are on a private cloud version that is lower than `1905` https://auth0.com/releases

**Comment by bpogrebi** [comment]
You are correct. Our appliance hasn't been updated to 1905 yet. I will go ahead and close this issue.
