### ISSUE TITLE
custom_login_page documentation and handling of missing file

### ISSUE THREAD

**Issue by mattjm** [auth0/auth0-deploy-cli#142]
Assuming tenant.yaml contains:

custom_login_page: myapplogin.html

(I think these two items are closely coupled enough to put in one issue)

### documentation issue:

CLI expects login page to be found in ./clients/myapplogin.html, relative to where you run the CLI tool.  If found, it loads the HTML contents of the file into custom_login_page in the client configuration object.  But this isn’t documented anywhere...you’d only know this if you had an existing custom login page and exported it via the CLI (or poked around in the code).

### error handling issue

If login page isn’t found in the location mentioned above, CLI puts the string “myapplogin.html” into custom_login_page in the client configuration object.  I think it would be better to either stop processing the import at this point, or at least insert some sort of error string so this doesn't look like a bug or problem with escaping.

**Comment by ronakvpanchal** [comment]
Need documentation for custom_login_page. There are details about this functionality and limitations around it.

**Comment by sergiught** [comment]
Apologies for the delay in getting to this! We finally have this available within https://github.com/auth0/auth0-deploy-cli/blob/master/docs/resource-specific-documentation.md

As such we'll be closing this down now.

**Comment by bejito** [comment]
I'm not sure to understand how the new documentation section solves this issue.

The doc explains how to setup a custom universal login page while @mattjm is talking about login pages custom to specific applications. I indeed managed to have it work following what he said about putting the html file in a `clients` folder and referring to it by name in `application[i].custom_login_page`. 

Is my understanding correct of did I miss something from the documentation page ?
