### ISSUE TITLE
Render variables in templated HTML on import

### ISSUE THREAD

**Issue by charlesjohnson** [auth0/auth0-deploy-cli#143]
Opened on behalf of @joberdick:

When using the Auth0 deploy-CLI to deploy a custom login page, "Interpolation of config variables do not render when using HTML via a file. 

(##DEV## does not render from the value in the config.json)"

Deploy-CLI should process the HTML for any config variables defined in config.json before uploading.

**Comment by alejandro-delgado-garcia** [comment]
Please we need this 🙏

**Comment by shushen** [comment]
Resolved by #296 and will be released shortly.
