### ISSUE TITLE
[Feature Request] Environment switching for same tenant/account

### ISSUE THREAD

**Issue by taras** [auth0/auth0-deploy-cli#147]
## Motivation

I'm contributing to a large project that relies very heavily on Preview Apps provided by Netlify. Preview Apps are demo sites that are created automatically for Pull Requests. The master branch serves as the production branch. 

In this setup, we don't have staging, functional testing or production environments per se. Any branch can be used by a customer if it offers value to them. Sometimes a branch could require Auth0 configuration that is unique to that branch. For example, we might want to add another app that is only available on that branch. 

I spent quite a bit of time trying to figure out how to get this working, but I realized that this is not possible without creating separate tenants/accounts for each branch. This is not workable because tenants can't be created via the API. 

## Approach

I would really love to see some kind of Environments setup that would allow me to specify a group of environment variables that would overwrite the settings of the account. Ideally, I would be able to add a file to a Pull Request that would override settings for that particular deployment of the application.

What are the changes that this could become possible in the near future?

FYI: I borrowed `Environment switching` terminology from the description in #86.

**Comment by zxan1285** [comment]
Hi!
You could use separate yaml file for each branch.
And run deploy-cli with `/auth0/branch-name/tenant.yaml` based on a branch name.

**Comment by taras** [comment]
Hi @zxan1285, 

Thank you for your suggestion. I want to make sure that we're on the same page about the outcome that we're looking for. Here is the workflow that we want to use.

1. We have *master* branch that publishes to example.com
2. Our repository has `auth0/tenant.json` file which provides Auth0 settings for example.com
3. When someone creates a pull request, the branch for that pull-request can be anything, like jira-1000-add-google-authentication. Netlify automatically creates a demo site with pull request number in the subdomain, let's say pr-1000-example-com.netlify.com
4. we would like to be able include changes to *auth0/tenant.json* in *jira-1000-add-google-authentication* branch and have it automatically apply to Auth0 configuration of pr-1000-example-com.netlify.com

If I understand correct, your suggestion to 
> use separate yaml file for each branch

Requires that we have a separate tenant/account for each branch otherwise when we run
> deploy-cli with /auth0/branch-name/tenant.yaml

It will override settings for example.com

Do I understand your suggestion correctly?

**Comment by zxan1285** [comment]
Yes, that's correct. If you want to use only one tenant, you have to override its settings each time. For example, you have `master/tenant.yaml` with all the default settings. For `jira-1000` you can copy `master/tenant.yaml` to `jira-1000/tenant.yaml` and add new clients, connections, rules, etc. Then deploy `jira-1000/tenant.yaml` to create new items without removing `master` items.

**Comment by taras** [comment]
I just want to make sure that you see that your suggestion is a workaround and equivalent alternative to the workflow that we're looking for. 

In summary, we need a way to create domain specific environments that override default tenant configuration. We want to use 1 tenant/account with multiple environments, not multiple tenants/environments.

**Comment by stevezau** [comment]
You may want to look using the YAML format and leverage templating language to auto inject things depending on env variables.

**Comment by willvedd** [comment]
@taras Is this something you're still trying to figure out? I think I'm trying to understand the rationale behind one tenant supporting multiple environments, without enforcing any separation, your environments are exposed to a collision or configuration overwrite. A more common development workflow is to create separate tenants for each environment, ex: dev, staging, prod.

**Comment by taras** [comment]
Yeah, no worries. The simulator gives us the ephemeral tenants that we need. If someone is looking for this, they can use our simulator since it's open source.
