### ISSUE TITLE
Enable seamless SSO not supported

### ISSUE THREAD

**Issue by tomyam1** [auth0/auth0-deploy-cli#150]
It seams that the "Enable seamless SSO" flag is not currently supported.

This might be because the management [API](https://auth0.com/docs/api/management/v2#!/Tenants/get_settings) doesn't list it.

But "Inactive timeout" and "Required log in after" are listed in the API and supported by deploy CLI as session_lifetime, idle_session_lifetime so this might be something you just missed.

![image](https://user-images.githubusercontent.com/3265649/63434446-c50c4980-c42d-11e9-82e1-4afd2699d866.png)

**Comment by zxan1285** [comment]
Hi @tomyam1 
`enable_sso` flag has been marked as read-only in v2.3.2 and won't be exported unless you manually include it using `INCLUDED_PROPS`.
Add `"INCLUDED_PROPS": { "tenant": [ "flags.enable_sso" ] }` to you config if you want to export that flag.

**Comment by tomyam1** [comment]
Thanks @zxan1285 
Works perfectly
