### ISSUE TITLE
Support passing in the tenant.yml via stdin when importing

### ISSUE THREAD

**Issue by bishtawi** [auth0/auth0-deploy-cli#156]
With the way my CI is set up, when running the import on the command line, it would be very helpful if I could pass in the tenant.yml data through stdin.

Something like `a0deploy import -i -`.

**Comment by willvedd** [comment]
Thanks for creating this issue. Unfortunately, we're looking ahead at the bugs and features we want to address in the near-term and this specific issue isn't slated for immediate development. However we have flagged it internally to look at in the coming quarters, including more mechanisms for passing in configuration. Stay tuned to our releases in the future, but for now I'm opting to close.
