### ISSUE TITLE
AUTH0_EXCLUDED_RULES will not preventing creating rules that are excluded

### ISSUE THREAD

**Issue by xiananfan** [auth0/auth0-deploy-cli#17]
From the readme:

> AUTH0_EXCLUDED_RULES
> This is a list of rule names that should be ignored by the deploy CLI. It will not delete, update or create rules that match those names.

But looking at the "updateRule" method in "auth0-source-control-extension-tools" [repo](https://github.com/auth0-extensions/auth0-source-control-extension-tools), the excluding of the script for certain rule happens after the creation of the rule, [code here](https://github.com/auth0-extensions/auth0-source-control-extension-tools/blob/master/src/auth0/rules.js#L111-L117). It seems like L111 already created the rule, which makes L114-L117 having no effect.

As a result of the above, the "AUTH0_EXCLUDED_RULES" will not prevent creating new rules that are excluded in the config.

Also, based on the current implementation of "applyMetadata" method [here](https://github.com/auth0-extensions/auth0-source-control-extension-tools/blob/master/src/auth0/rules.js#L91-L99), it doesn't care about the "isExcluded" variable, which means, when excluding an existing rule, if the rule was turned off in the admin console, but was set to enabled: true in the metadata, the deploy tool will actually turn it on despite it's excluded.

Is this expected behavior?

**Comment by mostekcm** [comment]
This actually won't be fixed until the pull request for this repo is complete
