### ISSUE TITLE
cli tool should highlight problems

### ISSUE THREAD

**Issue by ghost** [auth0/auth0-deploy-cli#174]
### Describe the problem you'd like to have solved
We started using this cli tool thinking it was an exact replacement for using the UI. It is not. 
This needs to be highlighted in the README file so others don't end up thinking the same thing.

### Describe the ideal solution
The cli tool does not support:
1 - The key/value pairs set up in rules under settings
2 - Machine to machine API authorized settings or any scope settings per API for an application.
3 - if the script fails, it may switch the configuration of the auth-cli-tool application so that it is no longer allowed access to the management API.

I know this because I tried (a few times) making changes in the UI to numbers 1 and 2 above and ran `a0deply export` and got no changes.
### Additional context
I am using the directory output.

**Comment by adrian-skybaker** [comment]
This would really improve the quality of the error messages when config is wrong.

**Comment by willvedd** [comment]
I'm closing this as it is not focused on a _specific_ issue. User, if these are still things that you'd like addressed, I recommend new, focused issues. That way, the team can better help address those specific issues directly.
