### ISSUE TITLE
auth0-deploy-cli@3.6.2 - Insufficient scope

### ISSUE THREAD

**Issue by valeriomazzeo** [auth0/auth0-deploy-cli#178]
This was working a couple of months ago - now:
```
error: Problem running command import during stage processChanges when processing type roles
error: {"statusCode":403,"error":"Forbidden","message":"Insufficient scope, expected any of: read:roles","errorCode":"insufficient_scope"}
The command "a0deploy import -c config-dev.json -i tenant.yaml" exited with 1.
```

**Comment by zxan1285** [comment]
Hey, @valeriomazzeo 
The `deploy-cli` can deploy `roles` now, so it requires new scopes. You can update `Auth0 Deploy CLI` extension if you're using one. If not, you'll have to update client_grans of deploy-cli's client in the dashboard.

**Comment by valeriomazzeo** [comment]
The extension is already updated and it's using 2.1.
I don't mind adding the roles myself, but the dashboard doesn't let me - I think it's related to the fact that the auth0 client is configured as "Generic" rather than "Machine-to-Machine".

Thoughts?

**Comment by zxan1285** [comment]
You should be able to change app type in settings:
<img width="547" alt="Screen Shot 2019-11-01 at 14 04 35" src="https://user-images.githubusercontent.com/20518477/68023671-86f29800-fcb0-11e9-9d43-c7fd1716bc74.png">
Or you can reinstall the extension (don't forget to update client id and secret in `deploy-cli` config).

**Comment by valeriomazzeo** [comment]
Yes, I was wondering whether it was intended to be done that way. It's this procedure documented anywhere?

**Comment by zxan1285** [comment]
No, updating the extension usually updates client grants as well. Not sure what could've go wrong there. I'm investigating that now.

**Comment by StephenCleary** [comment]
This happened again on 2020-12-24, with the error message `Error: Problem loading tenant data from Auth0 Forbidden: Insufficient scope, expected any of: read:actions`.

**Comment by fernandozpiccin** [comment]
I'm having similar issue with mfa_policies
I've open a community [post ](https://community.auth0.com/t/github-deploy-extension-insufficient-scope-expected-any-of-update-mfa-policies/56962) about.

**Comment by NishadKumar** [comment]
Hi, 

Thanks @StephenCleary @fernandozpiccin for raising this issue. I am having similar issues too. Any updates on this? So is the solution only to delete the auth0-deploy-cli extension and reinstall it? Doesn't it affect the existing client ID and client secret?

**Comment by StephenCleary** [comment]
I believe the extension is deprecated and cannot be (re-)installed. Instead, you should uninstall the extension and then follow [these instructions](https://github.com/auth0/auth0-deploy-cli#pre-requisites) to create the application by hand. #worked-for-me-at-least

**Comment by daboja** [comment]
Yes, same solution work for me (thanks @StephenCleary). I had deploy-cli extension installed (via extensions) long back, and had to remove it and then install again manually and make sure I grand all required permission listed below:

- create:client_grants
- delete:client_grants
- update:client_grants
- read:clients
- update:clients
- delete:clients
- create:clients
- read:client_keys
- update:client_keys
- delete:client_keys
- create:client_keys
- read:connections
- update:connections
- delete:connections
- create:connections
- read:resource_servers
- update:resource_servers
- delete:resource_servers
- create:resource_servers
- read:rules
- update:rules
- delete:rules
- create:rules
- read:hooks
- update:hooks
- delete:hooks
- create:hooks
- read:rules_configs
- update:rules_configs
- delete:rules_configs
- read:actions
- update:actions
- delete:actions
- create:actions
- read:email_provider
- update:email_provider
- delete:email_provider
- create:email_provider
- read:tenant_settings
- update:tenant_settings
- read:grants
- delete:grants
- read:guardian_factors
- update:guardian_factors
- read:mfa_policies
- update:mfa_policies
- read:email_templates
- create:email_templates
- update:email_templates
- read:roles
- update:roles
- delete:roles
- create:roles
- read:prompts
- update:prompts
- read:branding
- update:branding
- create:actions
- read:actions
- update:actions
- delete:actions

Additional permissions (to be granted as well):
- read:organizations
- update:organizations
- create:organizations
- delete:organizations
- create:organization_connections
- read:organization_connections
- update:organization_connections
- delete:organization_connections
