### ISSUE TITLE
CLI does not work well with node version 5.11.*

### ISSUE THREAD

**Issue by sgmeyer** [auth0/auth0-deploy-cli#18]
2017-08-22T20:27:33.343Z - error: uncaughtException: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode date=Tue Aug 22 2017 20:27:33 GMT+0000 (UTC), pid=224, uid=0, gid=0, cwd=/opt/atlassian/pipelines/agent/build, execPath=/usr/local/bin/node, version=v5.11.0, argv=[/usr/local/bin/node, /usr/local/bin/a0deploy, -i, ., -c, ./scripts/..//config.json], rss=59060224, heapTotal=41672992, heapUsed=29427408, loadavg=[11.93994140625, 9.75732421875, 8.58837890625], uptime=30824, trace=[
column=16, file=vm.js, function=exports.runInThisContext, line=53, method=runInThisContext, native=false, 
column=25, file=module.js, function=Module._compile, line=387, method=_compile, native=false, 
column=10, file=module.js, function=Module._extensions..js, line=422, method=.js, native=false, 
column=32, file=module.js, function=Module.load, line=357, method=load, native=false, 
column=12, file=module.js, function=Module._load, line=314, method=_load, native=false, 
column=17, file=module.js, function=Module.require, line=367, method=require, native=false, 
column=19, file=internal/module.js, function=require, line=20, method=null, native=false, 
column=15, file=/usr/local/lib/node_modules/auth0-deploy-cli/node_modules/auth0-source-control-extension-tools/src/auth0/rules.js, function=null, line=5, method=null, native=false, 
column=34, file=module.js, function=Module._compile, line=413, method=_compile, native=false, 
column=10, file=module.js, function=Module._extensions..js, line=422, method=.js, native=false, 
column=32, file=module.js, function=Module.load, line=357, method=load, native=false, 
column=12, file=module.js, function=Module._load, line=314, method=_load, native=false, 
column=17, file=module.js, function=Module.require, line=367, method=require, native=false, 
column=19, file=internal/module.js, function=require, line=20, method=null, native=false, 
column=77, file=/usr/local/lib/node_modules/auth0-deploy-cli/node_modules/auth0-source-control-extension-tools/src/auth0/index.js, function=null, line=1, method=null, native=false, 
column=34, file=module.js, function=Module._compile, line=413, method=_compile, native=false, 
column=10, file=module.js, function=Module._extensions..js, line=422, method=.js, native=false, 
column=32, file=module.js, function=Module.load, line=357, method=load, native=false, 
column=12, file=module.js, function=Module._load, line=314, method=_load, native=false, 
column=17, file=module.js, function=Module.require, line=367, method=require, native=false, 
column=19, file=internal/module.js, function=require, line=20, method=null, native=false, 
column=15, file=/usr/local/lib/node_modules/auth0-deploy-cli/node_modules/auth0-source-control-extension-tools/src/deploy.js, function=null, line=2, method=null, native=false, 
column=34, file=module.js, function=Module._compile, line=413, method=_compile, native=false, 
column=10, file=module.js, function=Module._extensions..js, line=422, method=.js, native=false, 
column=32, file=module.js, function=Module.load, line=357, method=load, native=false, 
column=12, file=module.js, function=Module._load, line=314, method=_load, native=false, 
column=17, file=module.js, function=Module.require, line=367, method=require, native=false, 
column=19, file=internal/module.js, function=require, line=20, method=null, native=false], stack=[SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode, at exports.runInThisContext (vm.js:53:16), at Module._compile (module.js:387:25), at Object.Module._extensions..js (module.js:422:10), at Module.load (module.js:357:32), at Function.Module._load (module.js:314:12), at Module.require (module.js:367:17), at require (internal/module.js:20:19), at Object.<anonymous> (/usr/local/lib/node_modules/auth0-deploy-cli/node_modules/auth0-source-control-extension-tools/src/auth0/rules.js:5:15), at Module._compile (module.js:413:34), at Object.Module._extensions..js (module.js:422:10), at Module.load (module.js:357:32), at Function.Module._load (module.js:314:12), at Module.require (module.js:367:17), at require (internal/module.js:20:19), at Object.<anonymous> (/usr/local/lib/node_modules/auth0-deploy-cli/node_modules/auth0-source-control-extension-tools/src/auth0/index.js:1:77), at Module._compile (module.js:413:34), at Object.Module._extensions..js (module.js:422:10), at Module.load (module.js:357:32), at Function.Module._load (module.js:314:12), at Module.require (module.js:367:17), at require (internal/module.js:20:19), at Object.<anonymous> (/usr/local/lib/node_modules/auth0-deploy-cli/node_modules/auth0-source-control-extension-tools/src/deploy.js:2:15), at Module._compile (module.js:413:34), at Object.Module._extensions..js (module.js:422:10), at Module.load (module.js:357:32), at Function.Module._load (module.js:314:12), at Module.require (module.js:367:17), at require (internal/module.js:20:19)]
npm info lifecycle dz-auth0-config@0.0.1~postdeploy: dz-auth0-config@0.0.1

**Comment by angarsky** [comment]
I get the same error. Even a test running (from the Overview page) fails.

**Comment by mostekcm** [comment]
Sorry, we only support 6.10 and above right now.  If anyone would like to submit a PR I'll review and merge it, but the underlying tools we use may not support it so I haven't investigated older versions of node.

**Comment by angarsky** [comment]
@mostekcm thanks for the reply. I will try to use younger node releases.
