### ISSUE TITLE
Problem exporting roles

### ISSUE THREAD

**Issue by willhackett** [auth0/auth0-deploy-cli#182]
### Description

> Unable to iterate over `{}` returned by `roles` in `context.assets`.

https://github.com/auth0/auth0-deploy-cli/blob/master/src/context/yaml/handlers/roles.js#L12

Suggestion:

`context.assets.roles instanceof Array ? context.assets.roles : []`

I've noticed a few things come back as objects so the OR expression probably isn't the best in this case.

### Reproduction

- Run `a0deploy export -c config.json -f yaml -o . -d true`

![image](https://user-images.githubusercontent.com/12025460/68259309-9a757880-008d-11ea-9228-fcaabbca1c91.png)

### Environment

> Please provide the following:

- **Version of this library used:** 3.6.3

**Comment by willhackett** [comment]
Let me know if you want a PR.

**Comment by aagavin** [comment]
Also running into the same issue

**Comment by TranquilMarmot** [comment]
We've run into this as well!
