### ISSUE TITLE
CLI Import breaks email provider configuration

### ISSUE THREAD

**Issue by MikeHixWork** [auth0/auth0-deploy-cli#187]
### Description

When running a command line import to a tenant, after the import is complete emails stop being sent and we get an error when trying that the security token in the request is invalid.  I'll copy one of these errors below.  I would expect the email configuration to continue working after an import.

### Reproduction

To reproduce:
1. Start with a tenant with a functioning email provider.  Specifically we are using Amazon SES.
2. Run an export of the local settings with the CLI tool.  (I can see in the provider.json that the credentials are overwritten with "YOUR_ACCESS_KEY_ID" and "YOUR_ACCESS_SECRET_KEY" on an export).  This step is presumably not needed if you haven't gone in and manually put the provider credentials into the provider.json.
3. Run an import, then try to send an email.  In the logs you will see a "Failed Sending Notification" event. 

4. Upon re entering the credentials for the Email Provider via the UI the emails start to function correctly again.

error contents are:

```
{
  "date": "2019-12-10T21:46:53.476Z",
  "type": "fn",
  "description": "To: my email was here",
  "connection_id": "",
  "details": {
    "email_type": "try_provider_configuration_email",
    "to": "my email was here",
    "error": "The security token included in the request is invalid."
  },
  "log_id": "90020191210214658742000842556561008765975695991198711938",
  "_id": "90020191210214658742000842556561008765975695991198711938",
  "isMobile": false,
  "user_agent": "Other 0.0.0 / Other 0.0.0"
}
```

### Environment

> Please provide the following:

- Version 3.6.3
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

**Comment by faroceann** [comment]
This is the expected behavior of the Deploy CLI. When secrets are imported, they are removed from the configuration. The recommended flow for customers is to export the tenant, modify the imported files to add the appropriate secrets, and then import the tenant.
