### ISSUE TITLE
Add support for missing database connection settings

### ISSUE THREAD

**Issue by schwer** [auth0/auth0-deploy-cli#19]
Lacking this, I can't keep my password complexity settings and/or password dictionary under revision control.

**Comment by stevezau** [comment]
With the new deploy-cli version 2 this is supported.

You can add options under the database connections for example
`    "options": {
      "passwordPolicy": "excellent",
      "password_history": {
        "enable": true,
        "size": 5
      },
      "password_dictionary": {
        "enable": true,
        "dictionary": [
          "test123"
        ]
      },
      "password_no_personal_info": {
        "enable": true
      },
      "password_complexity_options": {
        "min_length": 8
      }`
