### ISSUE TITLE
TypeScript declarations

### ISSUE THREAD

**Issue by TranquilMarmot** [auth0/auth0-deploy-cli#193]
### Describe the problem you'd like to have solved

There are no TypeScript declarations for this package! We want to use it programmatically with TypeScript but this is difficult without types.

### Describe the ideal solution

It would be nice to include declarations alongside the npm package, or they can be added to https://github.com/DefinitelyTyped/DefinitelyTyped under `@types/auth0-deploy-cli`

## Alternatives and current work-arounds

Currently, we just have `declare module 'auth0-deploy-cli';` which is basically just turning off type-checking for the library

**Comment by shawnmclean** [comment]
Hi @TranquilMarmot, I'd like to understand a bit more about how are you using the cli programmatically.  Do you mind sharing that info here or with our support?

**Comment by macdaddyaz** [comment]
@shawnmclean I'm currently building a DevOps process around our Auth0 tenants, using GitHub Actions. I'm creating a custom action in TypeScript which will load the CLI configuration file, the tenant configuration files, do some manipulation/normalization, and then invoke the CLI `deploy` function (at least, this is what I'm trying to do -- we'll see if I can get it to work).

For my needs, I think some simple type definitions would be helpful -- the `deploy` & `dump` functions along with their param object, and maybe even the top-level of the CLI config JSON format.

**Comment by TranquilMarmot** [comment]
That's almost exactly what we're doing with this library as well; lots of DevOps stuff around dumping/deploying using TypeScript.

**Comment by mikestopcontinues** [comment]
Ditto here. Using it programmatically helps me keep a bunch of params in sync across aws-cdk, vercel env vars, paddle products, and auth0 config. I've got types for everything else, either because they're provided or because I typed the API endpoints I use.

**Comment by zanebclark** [comment]
Excited to see this come to fruition!

**Comment by willvedd** [comment]
Good news folks, this has been added in our 7.8.0 release! I tested this quite a bit and believe it to cover most folks' use cases, but it may not be 100% perfect. Would be great to have folks give it a go and provide some feedback.

Samples:

```ts
import { dump, deploy } from 'auth0-deploy-cli';

await dump({
      output_folder: "./output",
      format: "yaml",
      config: {
        AUTH0_DOMAIN: "<YOUR_DOMAIN>",
        AUTH0_CLIENT_ID: "<YOUR_CLIENT_ID>",
        AUTH0_CLIENT_SECRET: "<YOUR_CLIENT_SECRET>"
   }
});
```
and 

```ts
import { dump, deploy } from 'auth0-deploy-cli';

await deploy({
      input_file: "./output/tenant.yaml",
      config: {
        AUTH0_DOMAIN: "<YOUR_DOMAIN>",
        AUTH0_CLIENT_ID: "<YOUR_CLIENT_ID>",
        AUTH0_CLIENT_SECRET: "<YOUR_CLIENT_SECRET>"
    }
});
```

I'm going to close but please feel empowered to provide feedback regarding refinement and fixes with new issues.
