### ISSUE TITLE
Webtask token and url

### ISSUE THREAD

**Issue by KostyaZgara** [auth0/auth0-deploy-cli#198]
Hi there! Thanks for working on a new version of the library and integrating hooks support. I have installed dev package 4.0.0-dev.17 but when I run deploy script I have the next issue:

![image](https://user-images.githubusercontent.com/18326076/72843707-c0311780-3ca3-11ea-9550-19da5cc2b04f.png)

Where I can found WEBTASK_API_TOKEN and WEBTASK_API_URL ? I made a research on https://webtask.io/ but nothing found and tried to log in but got an error on that site 

![image](https://user-images.githubusercontent.com/18326076/72843867-10a87500-3ca4-11ea-9851-eedce39191cc.png)

Can you help me?

P.S. I really appreciate your work and hope you will release the stable version with hook support in the nearest time.

**Comment by shawnmclean** [comment]
Hi @KostyaZgara, that version is no longer supported. The only version that will be close to our GA release is `4.0.0-dev.22` as that will use our new Hooks API  endpoints.

That version will, however, need a feature flag to be set on your tenant to enable its usage. We're in the process of removing those flags in preparation for releasing it to GA.

**Comment by charlesjohnson** [comment]
To echo what @shawnmclean said, the wait for GA will be days, not weeks. We appreciate you being patient while we enable this feature for everybody.

**Comment by charlesjohnson** [comment]
With the release of v4.0, the hooks API is now generally available to all customers using Auth0 public cloud. As a result we're closing this issue.
