### ISSUE TITLE
Removing permissions from roles not working

### ISSUE THREAD

**Issue by brense** [auth0/auth0-deploy-cli#199]
Removing permissions from a role by editing the associated .json file and running the import command does not actually remove the permission on the auth0 side even though it no longer exists in the json file.

The CLI tool indicates that it succesfully updated the role:
`2020-01-22T14:21:47.831Z - info: Updated [roles]: {"id":"rol_NkEF2gxq6lfUkjKn"}`
But the removed permission still exists when visiting auth0 and also still exists in the jwt token after requesting a new one.

- version: auth0-deploy-cli@3.6.7
- platform: node v12.14.1
- typescript: v3.7.5
- OS: win 10 v1809

**Comment by brense** [comment]
Oh, i forgot, the config i use:
```
{
  "AUTH0_DOMAIN": "*********************",
  "AUTH0_CLIENT_ID": "******************",
  "AUTH0_CLIENT_SECRET": "************************",
  "AUTH0_KEYWORD_REPLACE_MAPPINGS": {
    "AUTH0_TENANT_NAME": "***********************"
  },
  "AUTH0_ALLOW_DELETE": true
}
```

**Comment by willvedd** [comment]
@brense Thanks for opening this. The issue you described is certainly a bug, especially if you have the `AUTH0_ALLOW_DELETE` set as true. You're using a fairly old version of the CLI, would you be able to update and indicate if that fixes your issue? This functionality is a basic offering and without any other reports of this, I'm suspicious that this may be solved by updating or us double-checking your configuration. 

Are you able to update and provide feedback if that fixes your issue?

**Comment by willvedd** [comment]
Closing this issue because it's stale and even if it were a bug, I don't have reason to believe that this impacts current versions. I invite you to open a new ticket if this is still an active issue.
