### ISSUE TITLE
Version 4.0.0 not working on private tenants

### ISSUE THREAD

**Issue by mh-winkler** [auth0/auth0-deploy-cli#202]
### Description

When trying to use the version 4.0.0 of the tool on a private cloud instance, the tool returns a 404 error upon trying to fetch hooks.
When downgrading to 3.6.7, the tool runs as expected, and is able to export data from an tenant

### Reproduction

The error occurs, when running against a private cloud instance, using v.4.0.0
a0deploy export -c config.json -f yaml -o tmp

I suspect, the hooks api endpoints have not yet been released to private clouds, but I cannot see any details of these in our release notes, so I do not know when this will be release.

The CLI ought to handle the 404 gracefully instead of failing.

**Comment by lorenh** [comment]
Is this why I always get this when it gets to hooks?

:
2020-02-04T00:21:49.328Z - error: Problem running command export
2020-02-04T00:21:49.328Z - error: Problem exporting hooks

**Comment by mh-winkler** [comment]
It's the same error I saw, so I would suspect yes.
My guess is, that a new /hooks (or similar) endpoint has been enabled on the (public) tenants, but the tool does not gracefully handle the scenario where this is not yet present.

A temporary solution, is to downgrade to 3.6.7 - at least it was to me

**Comment by lorenh** [comment]
Just curious if it works when you try YAML output, that fixed it for me.  I was just getting started with the CLI, so I hadn't committed to YAML or directory format yet.  I think I prefer the YAML layout instead of gobs of files anyway.

**Comment by alejandro-delgado-garcia** [comment]
We are having the same issue on a private instance and indeed using version 3.6.7 works fine.

**Comment by mh-winkler** [comment]
@lorenh we only use the yaml format, so no - that wouldn't do it for us

**Comment by mh-winkler** [comment]
Upgrading to 4.0.1 seems to have fixed the issue
