### ISSUE TITLE
Delete warning when updating a hook

### ISSUE THREAD

**Issue by lorenh** [auth0/auth0-deploy-cli#204]
### Description

When importing from YAML I earlier exported using the CLI, a hook generated a warning saying the previous hook needs to be deleted.  Is this expected?  I guess I would have expected it to just replace a hook with the same name.

### Reproduction

See the warning below.  Yet other objects like rules seem to be able to just get updated without having to set the ALLOW DELETE flag.  Is this expected?  When I went into my tenant sure enough there were two hooks identically named.

```
2020-02-04T03:19:46.909Z - info: Getting access token for Y7u...
2020-02-04T03:19:47.776Z - info: Updated [rules]: {"name":"Rem...}
2020-02-04T03:19:49.607Z - warn: Detected the following hooks should be deleted. Doing so may be destructive.
You can enable deletes by setting 'AUTH0_ALLOW_DELETE' to true in the config

{"triggerId":"pre-user-registration"}

2020-02-04T03:19:50.410Z - info: Created [hooks]: {"name":"pre-user-registration-hook","triggerId":"pre-user-registration"}
```

### Environment

version 4.0.0

**Comment by lorenh** [comment]
It looks like updating the hook worked properly on subsequent import.  When I deleted the duplicate hook created the first time, and reran an import again, this time it seems to have worked. CLI generated no warning, and only one hook exists.  So maybe it's just a "first time" issue.

**Comment by lorenh** [comment]
I think this had something to do with the "id" originally assigned to my hook.  When I manually created the hook I think it had an id of something like "pre-user-registration-hook" which matched the name I gave it.

The CLI seems to have overridden that id and given it a new random id (which I can see when I export with ids)

'''
  - name: pre-user-registration-hook
    script: ./hooks/pre-user-registration-hook.js
    id: 01E073C5KDABJW8J1AN83FMREW
'''

Which is why I had two hooks with the same name after import.  I deleted the original one in the dashboard, and now everything's happy on repeated imports.

**Comment by willvedd** [comment]
@lorenh Thanks for opening this issue and documenting your issue thoroughly. To comment on your issue, yes, because you assigned an ID yourself that differed from the hook on your remote, the deploy CLI interpreted that as you creating a new hook. If you still feel as though this is an active issue, please feel free to open a new issue and we can discuss further.
