### ISSUE TITLE
Add documentation for error-handling / rollback

### ISSUE THREAD

**Issue by skjolber** [auth0/auth0-deploy-cli#212]
This tool looks great, but your git-based-extensions seems to have some error-handling (i.e. auto redeploy on error). So I'm wondering if there is some practical differences between them extensions and this command-line tool, and also how to do error-handling the right way. For example, is there a transaction-concept in the git-based-extensions, or do then use a tool like this under the hood?

### Describe the ideal solution

Docs on rollback / redeploy. Add a comparison toe git-based-extensions, if any.

## Alternatives and current work-arounds

Add homemade error-handling.

**Comment by willvedd** [comment]
@skjolber I've been mulling this over a bit. Can you outline how you think this would be best documented? To answer your question, the tool does not implement any type of concept of a transaction, and upon error, you'd almost always be advised to redeploy as the process is idempotent. Not that I expect users to know that, but it seems a little light on details and may seem out of place in our documentation. What do you think?

**Comment by willvedd** [comment]
Closing this one out. I have no problems adding to the documentation or improving error messaging, but I'd like to better understand the confusion here before I do. And FWIW, I haven't seen any other issues that suggest something similar. Apologies for the late response on this one though!
