### ISSUE TITLE
Database connections to client are exported despite AUTH0_EXCLUDED_CLIENTS

### ISSUE THREAD

**Issue by edibopp** [auth0/auth0-deploy-cli#214]
### Description

My Auth0 tenant has applications that are automatically generated by a service I control. The use case is to provide API credentials to users for their own integration with my API.

These applications are not part of the static configuration I want to manage with auth0-deploy-cli. Ideally auth0-deploy-cli should not interact with these at all. Therefore I used `AUTH0_EXCLUDED_CLIENTS` in the config. I expected the CLI to silently ignore anything related to these clients, i.e. to not pull anything related to them into the working directory during export and not update or delete them during import.

### Reproduction

We use this line in the config:

```js
{
  // ...
  AUTH0_EXCLUDED_CLIENTS: ['api-client'],
}
```

All the machine-generated applications are called `api-client`. This was done deliberately to catch them all using the `AUTH0_EXCLUDED_CLIENTS` feature. If I had to had to add them to the exclude list individually that would defeat the purpose of this approach, which is not to change the config for every automatically generated client.

When I export from Auth0 to the filesystem, the clients come up in two places. First, the database connections in `./database-connections/Username-Password-Authentication/database.json` have additional enabled clients:

```js
{
  // ...
  "enabled_clients": [
    "api-client",
    "api-client",
    // many more of the same api-client entries and other static applications...
  ],
  // ...
}
```

There is also a new grant relating the clients to an audience in `./grants`, but that was already reported in #144.

### Environment

- **Version of this library used:** auth0-deploy-cli 3.6.3
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):** Node 10.17.0
- **Other modules/plugins/libraries that might be involved:**

**Comment by seejee** [comment]
Hi there! Sorry it's taken so long to get back to you on this.

A note about the AUTH0_EXCLUDED_CLIENTS config option (as well as all the other AUTH0_EXCLUDED_* options):

They are only excluded on the _import_ process. We don't exclude anything on the export, so regardless of what is excluded, it will end up in your exported data.

We are considering changing this, but it would be a breaking change for some folks who might expect all the data (excluded or not) to end up in the export. If we decide to make the change, I'll let you know.

Thanks for taking the time to provide us with feedback!

**Comment by edibopp** [comment]
Hi @seejee. Thanks for the feedback. I don't work with Auth0 at the moment, as I changed companies, but it seems there are other people interested in the issue.

**Comment by urosgruber** [comment]
Would it be possible to exclude on _export_ as well but have a _cmd line_ flag to ignore excludes to work if needed?
