### ISSUE TITLE
Add support for elevating specified connections to be domain level connections

### ISSUE THREAD

**Issue by sidneyshek** [auth0/auth0-deploy-cli#22]
This is currently one of the remaining manual configuration steps we have for our database connection.

This perhaps is a general request for more configurability of connections.

**Comment by stevezau** [comment]
Hi @sidneyshek we just released a refactored deploy-cli with supports for more objects in Auth0.

Can you describe a bit more what you mean by `support for elevating specified connections to be domain level connections` ?

**Comment by fyockm** [comment]
Closing this issue because it is stale. Please reopen if this request is not covered by Deploy CLI v2.
