### ISSUE TITLE
Unable to update a database connection

### ISSUE THREAD

**Issue by sharmajyo** [auth0/auth0-deploy-cli#221]
### Description
unable to update a database connection when deploy called programmatically. 

### Reproduction
I have bellow json file in my connections folder

```
{
  "name": "default",
  "strategy": "auth0",
  "options": {
    "brute_force_protection": false,
    "passwordPolicy": "good",
    "requires_username": false,
    "disable_signup": true
  },
  "is_domain_connection": false,
  "enabled_clients": [
    "my-test-client"
  ]
}
```
 when running **deploy** from build process, all other resources get created/updated in auth0 tenant but for the database connection file above, a connection gets created and I get a warning 

`warn: Detected the following databases should be deleted. Doing so may be destructive.`

later on re-running the build process(which calls deploy), I get following error
`{"statusCode":409,"error":"Conflict","message":"A connection with the same name already exists","errorCode":"connection_conflict"}`

### Environment

- **Version of this library used:**  4.2.0
- **OS** mac
- **node** 10

**Comment by willvedd** [comment]
@sharmajyo Is this still an issue that you're running into? I believe that versions released since this ticket would have solved your issue.

**Comment by willvedd** [comment]
Thanks for opening this and apologies for the delay to respond. I'm opting to close this as I don't believe it's an issue anymore and doesn't appear to be actionable on our end. If this is something you're still experiencing, please open a new ticket and we can help support you with newer information.
