### ISSUE TITLE
installation problem due to express-jwt

### ISSUE THREAD

**Issue by smarajitdasgupta** [auth0/auth0-deploy-cli#23]
`npm i -g auth0-deploy-cli ` doesn't complete due to express-jwt error

`npm ERR! 404 Not Found: @types/express-jwt@0.0.34`

I am using node v8

**Comment by stevezau** [comment]
Can you please try again, we have released a new version 2.0.

**Comment by fyockm** [comment]
Closing this issue because it is stale. Please reopen if your error was not fixed with Deploy CLI v2.
