### ISSUE TITLE
Inconsistent import behavior between directory and yaml formats can lead to tenant being wiped of all configuration.

### ISSUE THREAD

**Issue by suwyn** [auth0/auth0-deploy-cli#231]
### Description

Importing a directory configuration where the directory is missing a directory for a handler results in the import deleting all resources for the handler on the tenant.

This behavior is different for a yaml configuration, where the absence of a handler key in the yaml will **not** delete resources for that handler.

This issue caused us problems when we deployed an empty directory to a tenant.  The result was all resources of that tenant were deleted.

Expected behavior would be for no resources to be deleted unless an empty directory for that resource was present in the directory being deployed.

### Reproduction

**Behavior with Directory format**
1. Export a configuration in directory format.
2. Delete the `resource-servers` folder (or any of the folders)
3. Import the directory back into the tenant.
4. You'll either see a message that the resources could be deleted, or they will be deleted, based on `AUTH0_ALLOW_DELETE`

**Behavior with YAML format**
1. Export a configuration in YAML format.
2. Delete the `resource-servers` key in `tenant.yaml`
3. Import the yaml back into the tenant.
4. The resources for the key that was removed are not processed for deletion.

The differences is observed in `context.load()` where the directory format returns an empty array for the asset `resourceServers: []` and the yaml format will return `resourceServers: undefined`

### Environment

- Version: `4.2.1`

**Comment by ojkelly-vha** [comment]
I'd probably expect it would delete them (how else would you clean up after yourself)?

I think if this behaviour either way was behind a flag it would be helpful. But as it is, with a full GitOps workflow this would be the only way to remove anything from your tenant, so it needs to be possible.

**Comment by shushen** [comment]
Fixed by #234. Thanks for the report and the PR!
