### ISSUE TITLE
mkdirp dependency missing

### ISSUE THREAD

**Issue by 7opf** [auth0/auth0-deploy-cli#239]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

> Provide a clear and concise description of the issue, including what you expected to happen.

Installing auth0-deploy-cli as a dev-dependency fails to install mkdirp module which causes the export command to fail.

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.

### Environment

> Please provide the following:

affects today's release of 4.3.0

**Comment by adamtickner** [comment]
Same issue for me on Mac/Windows/WSL if that is any use.

**Comment by hjensendev** [comment]
Same issue on Ubuntu. Version 4.2.2 still works.

**Comment by MarcusBaker-Auth0** [comment]
Hi, we encountered this today and were able to work around it by installing the package globally:

npm i -g mkdirp@latest

**Comment by shawnmclean** [comment]
Fixed in https://github.com/auth0/auth0-deploy-cli/pull/241

Released in 4.3.1: https://github.com/auth0/auth0-deploy-cli/releases/tag/v4.3.1
