### ISSUE TITLE
Help with log describing deletion of 1 client

### ISSUE THREAD

**Issue by emsearcy** [auth0/auth0-deploy-cli#25]
When I run a0deploy with debug output, against the configuration created by a0dump, it says "If implemented would be Deleting 1 clients".

My concern is that at some point in the future this gets implemented and then something is deleted, so I was trying to figure out what it was!

I don't have a json file for my "Deploy" client (a0dump didn't create one) ... is that what this is referring to?

Or ... looking in the local state, I noticed this reference:

```
"adds": {},
"deletes": [
  "All Applications"
],
"updates": {...}
```

...is this a bug where "All Applications" is somehow being queued as a (not-yet-supported) deletion?

**Comment by stevezau** [comment]
Hi @emsearcy and @kschulst, the new version of deploy-cli which has more verbose output. It also forces a user to set AUTH0_ALLOW_DELETE env var prior to deleting anything.
