### ISSUE TITLE
Support (create/delete) for Anomaly Detection Shields

### ISSUE THREAD

**Issue by jatinvaidya** [auth0/auth0-deploy-cli#250]
### Describe the problem you'd like to have solved

Please include support (creation, deletion) for the Anomaly Detection shields (see attached screenshots).

### Describe the ideal solution

There are currently Management API for CRUD of Anomaly Detection shields and triggers as follows:

1. GET /api/v2/anomaly/shields
2. GET /api/v2/anomaly/triggers
3. DELETE /api/v2/anomaly/shields/:id
4. POST /api/v2/anomaly/shields
{
  "action": "block|notify",
  "trigger": "${trigger_id}"
}

## Alternatives and current work-arounds

Use of management API directly, outside of `auth0-deploy-cli` as mentioned above.

### Additional context

> Add any other context or screenshots about the feature request here.
![image](https://user-images.githubusercontent.com/6619549/83841881-0e235500-a745-11ea-98cb-3bc71a68cfd6.png)

**Comment by mendhak** [comment]
Hi Auth0, would appreciate if this issue got some attention.  We're using the Auth0 Deploy CLI but having to manage the Attack Protection by hand.

**Comment by RileyMathews** [comment]
We would also appreciate this feature as well! We are currently looking into enabling and configuring out attack protections and it was a little disappointing to see we cannot manage them through the deploy CLI which up until now has served all of our configuration needs.

**Comment by willvedd** [comment]
Thanks for opening this ticket and apologies for the delayed response. Anomaly detection has since been rebranded as "attack protection" which has recently been implemented into the Deploy CLI since [7.5.0](https://github.com/auth0/auth0-deploy-cli/releases/tag/v7.5.0). Please update and give it a go!
