### ISSUE TITLE
Support (create/update/delete) for Log Streams

### ISSUE THREAD

**Issue by cv711** [auth0/auth0-deploy-cli#254]
### Describe the problem you'd like to have solved

Please include support for the creation and deletion of Log Streams.

### Describe the ideal solution

There are currently Management API for CRUD of Log Streams as follows:

1. GET /api/v2/log-streams
2. POST /api/v2/log-streams
3. GET /api/v2/log-streams/{id}
4. DELETE /api/v2/log-streams/{id}
5. PATCH /api/v2/log-streams/{id}

## Alternatives and current work-arounds

Use of management API directly, outside of `auth0-deploy-cli` as mentioned above.

**Comment by mmajkafmp** [comment]
This feature would e definitely a good addition!

**Comment by willvedd** [comment]
Good news folks, log streams management support has been added with the [v7.9.0 release](https://github.com/auth0/auth0-deploy-cli/releases/tag/v7.9.0). Please upgrade and give it a go! I was unable to test all external integrations besides Azure Event Grid integration, so if anyone can test that Azure integration and follow-up, that would be great. If any specific issues arise with this new support, please create a new ticket.
