### ISSUE TITLE
The slack message is a bit funky

### ISSUE THREAD

**Issue by kschulst** [auth0/auth0-deploy-cli#27]
I see something like this:

**auth0-deployments APP [21:18]**
Source-control to Auth0 Deployment (<undefined/login|Details>)
Tool: Auth0 Deploy CLI
Host: e4900587-aa24-4e1d-4eea-c40ceaf4571c
Username: root
Date/Time: 2018-04-17T19:18:33+00:00
Rules Updated: 3
Clients Updated: 9

The "undefined" comes from the WT_URL property not being set. (WT_URL is not documented in the readme.)

Also, including hints about which Auth tenant would be helpful.

Even better, an option to include whichever property from the config file or environment would be very helpful.

As a "hack" for now I am tempted to set the WT_URL config value in order to be able to see which Auth0 tenant the deploy is being done for.

**Comment by fyockm** [comment]
Closing this issue because it is stale. Please reopen if your error was not fixed with Deploy CLI v2.
