### ISSUE TITLE
guardianFactorProviders section doesn't allow setting phone-message-hook as provider. 

### ISSUE THREAD

**Issue by saltukalakus** [auth0/auth0-deploy-cli#274]
### Description

It seems that with **guardianFactorProviders** it isn't possible to set **phone-message-hook** with **provider** attribute. I can set it with **guardianPhoneFactorSelectedProvider** though and it helps to configure the tenant correctly for custom SMS provider. However, the missing option of **phone-message-hook** for **guardianFactorProviders**  may cause confusion.
 
### Reproduction

When I configure a custom SMS provider with the hook and export the configuration, the provider is set to **twilio**  for **guardianFactorProviders**.

<img width="570" alt="Screen Shot 2020-08-24 at 21 59 56" src="https://user-images.githubusercontent.com/815705/91084947-650a3d80-e655-11ea-9df7-74af95e9d721.png">

If I use the exported configuration to import, it works and I can see that the custom SMS provider with a phone hook is configured correctly. But, if I set **phone-message-hook** as provider, cli throws an error stating that the provider field in **guardianFactorProviders** only allows setting **twilio**  or **sns**. 

<img width="1126" alt="Screen Shot 2020-08-24 at 22 11 13" src="https://user-images.githubusercontent.com/815705/91085993-ec0be580-e656-11ea-81f4-97077974d604.png">

It seems that you had applied a fix for missing support for SMS hooks on [this issue](https://github.com/auth0/auth0-deploy-cli/issues/237). This one is mostly for cosmetic enhancement to prevent confusion by allowing **phone-message-hook** with  **guardianFactorProviders** if possible. 

To be honest, I'm not fully sure if this issue is caused by the underlying management API or CLI itself. If it is API limitation please let me know.

### Environment

5.1.5 of deploy CLI.

**Comment by kb-coder** [comment]
Any update on a fix for this?

**Comment by yvovandoorn** [comment]
@kb-coder and @saltukalakus this should be resolved in the current (5.3.1) release.

**Comment by shushen** [comment]
Marking as resolved in v5.3.1+
