### ISSUE TITLE
Universal Login maintenance

### ISSUE THREAD

**Issue by nason** [auth0/auth0-deploy-cli#276]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I'd like to be able to manage my tenant's universal login page template with this CLI

https://auth0.com/docs/universal-login/new-experience/universal-login-page-templates

### Describe the ideal solution

The CLI imports and exports universal login page templates, and possibly other branding configuration

## Alternatives and current work-arounds

Currently, the only way we can manage these settings is manually via API.

We're considering scripting some kind of sync but it would be much better if this was managed by this CLI with the rest of our config

**Comment by tyroneerasmus** [comment]
Just ran into this limitation too.

Anyone have any cobbled together scripts for doing this they can share? Otherwise I guess I am coding this for our CI/CD process and making it sit alongside our invocations of `a0deploy`

**Comment by SAGV** [comment]
We are also hitting the limitation :-(

**Comment by willvedd** [comment]
Folks, thanks for the feedback around this. It's definitely a reasonable request to manage all aspects of the universal login experience. There are a few nuanced technical reasons why I suspect this hasn't been implemented up to this point, but I'll spare you the explanation. But rest assured, we're looking closely at this project and its deficiencies, including this specific issue.

**Comment by willvedd** [comment]
As noted in #315, the favicon URL should be a supported configuration to include under this general issue.

**Comment by willvedd** [comment]
Good news folks, this has been added in the [7.6.0](https://github.com/auth0/auth0-deploy-cli/releases/tag/v7.6.0) release! Please upgrade and give it a go. If any issues arise, feel empowered to make an issue.

**Comment by zebapy** [comment]
it's annoying that it requires a customized domain to pull settings though I can modify the settings in the UI.
