### ISSUE TITLE
examples and tests for guardian/policies.json are slightly wrong

### ISSUE THREAD

**Issue by smcl** [auth0/auth0-deploy-cli#277]
### Description

We wanted to use the auth0 deploy CLI to force MFA for all our applications, however we based our settings on the examples & tests, which are wrong. 

Firstly if I deploy our tenant settings using the same contents as the example `/guardian/policies.json` (which is `["all-applications"]`) I get the below result:

    $ a0deploy import -c config.json -i .
    2020-09-11T14:58:14.137Z - info: Processing directory .
    2020-09-11T14:58:14.157Z - info: Getting access token for (DELETED)/(OUR-TENANT).eu.auth0.com
    2020-09-11T14:58:14.221Z - error: Problem running command import
    2020-09-11T14:58:14.221Z - error: Schema validation failed loading [
        {
            "keyword": "type",
            "dataPath": ".guardianPolicies",
            "schemaPath": "#/properties/guardianPolicies/type",
            "params": {
                "type": "object"
            },
            "message": "should be object"
        }
    ]

It appears that the actual contents of policies.json should be the following:

    {
      "policies": [ 
        "all-applications"
      ]
    }

Additionally I believe some of the tests - in `/test/context/directory/guardianPolicies.test.js` - use the wrong value. They contain "all-application" (note: missing "s"). This should really be changed in case anyone refers to these in future and erroneously believes them to contain the right value. 

### Reproduction

Deploy auth0 settings for a tenant using `a0deploy import -i .` inside a directory with a `/guardian/policies.json` set to the following:

    [
      "all-applications"
    ]

### Environment

We're using auth0 deploy CLI v5.1.5 and node.js v14 under Alpine Linux.

**Comment by shushen** [comment]
Fixed by #278
