### ISSUE TITLE
Add support for configuring Rules configuration params

### ISSUE THREAD

**Issue by kschulst** [auth0/auth0-deploy-cli#28]
Ref https://github.com/auth0-extensions/auth0-source-control-extension-tools/commit/ae7ab3994a81d2bed70d6b600b6f0d609d7b6766

Seems that the only thing that needs to be done for this to work is to update the "context" initialization (reading ruleConfigs files).

**Comment by stevezau** [comment]
This is now supported in v2. Please see the latest readme and example directory
