### ISSUE TITLE
Change Username action script for Custom Database Connection not supported

### ISSUE THREAD

**Issue by PeterGFernandez** [auth0/auth0-deploy-cli#284]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Whilst a Custom Database Connection in Auth0 supports use of a `change_username` script, the Deploy CLI does not recognise `change_username.js` as a valid script file, even though `change_username` is supported in the `customScripts` section of database.json. This inconsistency results in an error condition when trying to execute change username functionality for a Custom Database Connection.

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> Where applicable, please include:
>
> - Code sample to reproduce the issue
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

Attempt to import a Custom Database Connection which has a `change_username.js` script file and a `change_username` entry in the `customScripts` section of database.json. 

### Environment

> Please provide the following:

- **Version of this library used:**
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

Latest version of the tool

**Comment by willvedd** [comment]
Following up –  the `change_username` is not undocumented for any particular reason. This tells me that its usage is safe, not deprecated and not necessarily subject to any future change. If any folks still have issues managing this custom script, please feel empowered to create a new ticket.
