### ISSUE TITLE
Document all possible config keys

### ISSUE THREAD

**Issue by avnerenv0** [auth0/auth0-deploy-cli#286]
### Describe the problem you'd like to have solved

I stumbled on the `AUTH0_EXCLUDED_CONNECTIONS` configuration property and it really helped me use this library better. But I really found it by accident. I'd like all config options to be documented.

### Describe the ideal solution

Document all config options in the README (or a linked MD file)

**Comment by okeegan-myob** [comment]
You have my +1 (though if I could +100 to this, I would). I really want to understand what `AUTH0_ALLOW_DELETE` will actually do. I understand it to be like the aws s3 sync with --delete but it would be great to have it explicitly described.

**Comment by bfricka** [comment]
At the bare minimum, create a public JSON schema. This is good for the project as well since it can be used for validation. Considering the absolute neglect of the issues in the project, it's hard to see it happening anytime soon, though.

**Comment by willvedd** [comment]
Update: this is being worked on right now (better late than never)! Looking forward to sharing with folks very soon.

**Comment by willvedd** [comment]
This has been addressed with the addition of documentation to this project, including a [Configuring the Deploy CLI page](https://github.com/auth0/auth0-deploy-cli/blob/master/docs/configuring-the-deploy-cli.md). Please check it out and create PRs with any suggested alterations. Thanks for everyone's patience!
