### ISSUE TITLE
No resource with identifier No resource with identifier Auth0 Management API

### ISSUE THREAD

**Issue by garthk** [auth0/auth0-deploy-cli#29]
I can't grant a client access to the Auth0 management API by specifying, in `clients/zzzz.meta.json`, either:

* `grants["Auth0 Management API"]`
* `grants["278ad02cf7254e85b03e29ee"]` where that's the ID of the management API for that tenant

`a0deploy` crashes out with:
```
2018-04-24T04:01:44.709Z - error: Exiting due to error: "No resource with identifier Auth0 Management API"
2018-04-24T04:01:44.710Z - error: Not Found: No resource with identifier Auth0 Management API
```

`GET https://xxxx.yy.auth0.com/api/v2/resource-servers` → `200 OK` with:
```
[
  {
    "id": "278ad02cf7254e85b03e29ee",
    "name": "Auth0 Management API",
    "identifier": "https://xxxx.yy.auth0.com/api/v2/",
…
```

Workaround: using `identifier` does work, so you can wrap your tenant URL's `api/v2` as above and substitute it with `AUTH0_KEYWORD_REPLACE_MAPPINGS` in your configuration JSON:

```
{
  "AUTH0_DOMAIN": "xxxx.yy.auth0.com",
  "AUTH0_CLIENT_ID": "…",
  "AUTH0_KEYWORD_REPLACE_MAPPINGS": {
    "AUTH0_MANAGEMENT_API_IDENTIFIER": "https://xxxx.yy.auth0.com/api/v2/",
…
```

… then, in your `client.meta.json`:
```json
{
  "grants": {
    "##AUTH0_MANAGEMENT_API_IDENTIFIER##": [
      "read:users"
    ]
  }
}
```

**Comment by shawnmclean** [comment]
Hi @garthk the new version (2.0+) should help with this.
