### ISSUE TITLE
Error updating hook based on code present in existing hook

### ISSUE THREAD

**Issue by Duckslayer** [auth0/auth0-deploy-cli#290]
### Description
When updating a hook containing certain code using the deploy cli, the update fails.

### Reproduction
![image](https://user-images.githubusercontent.com/1542180/99234207-8746ce00-27f4-11eb-9d45-6e4bd9edd184.png)

Deploying this code with the CLI works fine. However, when running the same deploy again, it breaks. I am only deploying this and some Rules (importing from directories), and this is the part that does not work. From what I gather, deployment of hooks fails if some faulty code is already present within the hook. If you manually delete the hook, deployment works again. Allow delete is set to false.

A second run of the import command produces this:
![image](https://user-images.githubusercontent.com/1542180/99234314-a9d8e700-27f4-11eb-88d1-be4f20b1c897.png)

Changing the code in the hook to the following fixed the issue:
![image](https://user-images.githubusercontent.com/1542180/99234352-b52c1280-27f4-11eb-8032-94cdaa373857.png)

I speculate that it has something to do with the callbacks, branching etc. But I could not figure out how to properly structure it so deployment worked. And even if my code was faulty, I’d expect it to either deploy anyway or fail on first deploy. And I would also expect a better error message.

### Environment

Deploy CLI version is 5.2.1

**Comment by willvedd** [comment]
@Duckslayer is this still an active issue for you? My suspicion is that this error is generated by the API, not the deploy CLI itself. Happy to look at it if you're still having trouble with this.

**Comment by willvedd** [comment]
Thanks for taking the time to open this issue. Sorry that it's sat for so long, but going to close because it's stale and as far as I can tell, unactionable. If anyone is still experiencing this issue or something similar, please feel empowered to open a new issue!
