### ISSUE TITLE
Keyword replace mappings are not working with custom html pages

### ISSUE THREAD

**Issue by alejandro-delgado-garcia** [auth0/auth0-deploy-cli#291]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

We are trying to use the key `AUTH0_KEYWORD_REPLACE_MAPPINGS` to parameterize the HTML content of our custom login pages that we can set a client level using this property `"custom_login_page": "./login.html"`

### Reproduction

For instance, if we have this:

On `login.html`
```
<!DOCTYPE html>
<html lang="en">
  <head></head>
  <body>
   <a href="##FORGOT_PASSWORD_URL##" data-i18n="forgotPassword">Forgot password?</a>
  </body>
</html>
```

So once we deploy our config the replacement is not happening and we do have the key in our config file.

We would like to replace the value depending on the environment but this is not working for these HTML pages. We are successfully using these keyword replacements in other places but so far we haven't been able to do it here.

Thanks

### Environment

- Auth0 Deploy CLI tool 5.3.1
- node:10-alpine

**Comment by shushen** [comment]
Resolved in #296
