### ISSUE TITLE
Option to log as JSON

### ISSUE THREAD

**Issue by KurtMar** [auth0/auth0-deploy-cli#300]
### Describe the problem you'd like to have solved

Logging is done using winston to stdout and stderr as strings and cannot be configured. While stdout and stderr are acceptable to us, our logs need to be in JSON format.

### Describe the ideal solution

Ideally when used programmatically we should be able to pass a custom logging function, so we can use our own logging framework.

## Alternatives and current work-arounds

No current workaround seems to exist. At minimum an environment variable should exist that would change the winston configuration: 
{
    timestamp: true,
    level: process.env.AUTH0_LOG || 'info',
    handleExceptions: true,
    json: !!process.env.AUTH0_LOG_FORMAT_JSON,
    colorize: !process.env.AUTH0_LOG_FORMAT_JSON
}
### Additional context

None

**Comment by willvedd** [comment]
@KurtMar Thanks for opening this ticket. While logging out to JSON is certainly a good idea, it's not slated for the roadmap of this project. We'd be happy to receive a PR for this feature, but don't think we realistically have the bandwidth to address ourselves given that there are several high-impact bugs and features still left to address. If you've come up with some workaround in the interim, please report back!
