### ISSUE TITLE
Cannot import. Value webauthn-roaming interpreted as invalid enum

### ISSUE THREAD

**Issue by daveanders** [auth0/auth0-deploy-cli#308]
### Description
We get this error message every time we try to export configuration from Auth0 tenant and import it.

```
Schema validation failed loading [
    {
        "keyword": "enum",
        "dataPath": ".guardianFactors[5].name",
        "schemaPath": "#/properties/guardianFactors/items/properties/name/enum",
        "params": {
            "allowedValues": [
                "sms",
                "push-notification",
                "otp",
                "email",
                "duo"
            ]
        },
        "message": "should be equal to one of the allowed values"
    }
]
```

### Reproduction
Export configuration from existing tenant and try to reimport it into same or another tenant.

### Environment
Deploy CLI tool V5.3.2
Deploy CLI extension 6.0 (under extensions in all our Auth0 tenants)

**Comment by daveanders** [comment]
After investigating more, it looks like the JSON validation table does not have entry for webauthn-roaming.

**Comment by mstssk** [comment]
I have a same problem.

ref
https://github.com/auth0/auth0-deploy-cli/issues/288
https://github.com/auth0/auth0-deploy-cli/issues/302

**Comment by daveanders** [comment]
Works with latest version 5.5.0
