### ISSUE TITLE
Create/delete connection

### ISSUE THREAD

**Issue by PierreCavalet** [auth0/auth0-deploy-cli#31]
Hi,

I want my CI to be able to create (and remove) connections on demand. I see that there is an endpoint in the management API: https://auth0.com/docs/api/management/v2#!/Connections/post_connections

Is there a reason why this CLI does not support connection creation and deletion ?

**Comment by fyockm** [comment]
@PierreCavalet there is no particular reason not to support `connections`. That functionality was just not requested before. PRs welcome. Note that the underlying dependency [auth0-source-control-extension-tools](https://github.com/auth0-extensions/auth0-source-control-extension-tools) would also need to be updated accordingly.

**Comment by stevezau** [comment]
This is now supported in v2. Please see the latest readme and example directory
