### ISSUE TITLE
Adaptive MFA in yaml import

### ISSUE THREAD

**Issue by okeegan-myob** [auth0/auth0-deploy-cli#311]
### Describe the problem you'd like to have solved

We are interested in enabling the adaptive multifactor functionality on our tenant, but we are nervous that it will be forgotten/overwritten if not stored in the tenant config yaml like the rest of our configuration. Please can you add something (maybe a flag?) to the auth0 deploy cli so that we can enable it in our config as code.

### Describe the ideal solution

A flag or other key in the configuration that we can set to true for our tenant. Or changing the existing multifactor flag to add 'adaptive'.

## Alternatives and current work-arounds

Alternative is turning it on manually in the dashboard, but we would like to avoid this.

**Comment by shohremansourimyob** [comment]
If you add the below lines to your `tenant.yml` for deployment, it will turn on the Adaptive MFA:
```
guardianPolicies:
  policies:
    - confidence-score

```
