### ISSUE TITLE
Customise prompt text for Universal Login pages

### ISSUE THREAD

**Issue by tyroneerasmus** [auth0/auth0-deploy-cli#314]
### Describe the problem you'd like to have solved

I'd like to be able to customize text for the universal login page prompts with this CLI

https://auth0.com/docs/universal-login/new-experience/text-customization-new-universal-login

Related to a similar request for controlling Universal Login Page Templates (see #276)

### Describe the ideal solution

The CLI imports and exports prompt configuration

## Alternatives and current work-arounds

Currently, the only way we can manage these settings is manually via API.

We're considering scripting some kind of sync but it would be much better if this was managed by this CLI with the rest of our config

**Comment by willvedd** [comment]
@tyroneerasmus Do you feel as though this is the same as #276 ? I feel as though there could be a single general issue revolving around the maintenance of universal login.

**Comment by tyroneerasmus** [comment]
@willvedd yes it is probably the same thing: wanting to control all aspects of universal login from the CLI and not having to run scripts alongside the CLI that perform API calls

**Comment by willvedd** [comment]
Thanks for the feedback. I can certainly understand the use case here and absolutely reasonable to expect this CLI to support it. I'm going to close this ticket in favor of #276 as it helps me and the team organize around this functionality.

**Comment by jasonfagerberg-toast** [comment]
@willvedd From what I can tell this is still not supported in release 7.6+ https://github.com/auth0/auth0-deploy-cli#auth0-deploy-cli but #276 is closed. Any chance this can be added as well?
