### ISSUE TITLE
Cannot set favicon_url in universal_login block

### ISSUE THREAD

**Issue by kennyjwilli** [auth0/auth0-deploy-cli#315]
### Description

I expected my branding to be updated with my `favicon_url`. Instead, the below errors were logged and the favicon_url was not set.

```
2021-01-31T17:47:43.000Z - error: Problem running command import during stage processChanges when processing type tenant
2021-01-31T17:47:43.000Z - error: Payload validation error: 'Additional properties not allowed: favicon_url' on property universal_login (Universal login customization settings).
```

According the the `/api/v2/branding` [documentation](https://auth0.com/docs/api/management/v2#!/Branding/patch_branding), I should be able to set `favicon_url`. I am able to set this property if I issue a separate API request. 

### Reproduction

I have the following block in my `tenant.json`

```json
  "universal_login": {
    "favicon_url": "https://example.com/my-favicon.svg",
    "colors": {
      "page_background": "#F9F9FA",
      "primary": "#0071E5"
    }
  }
```

Run `a0deploy import`. Observe the logged errors. 

### Environment

- **Version of this library used:** 5.5.0

**Comment by willvedd** [comment]
Thanks for the feedback. This is certainly a reasonable ask for this tool. However, I'm opting to close in favor of #276 which is a more general issue around all aspects of universal login, including favicon URL.
