### ISSUE TITLE
Handling connection secrets

### ISSUE THREAD

**Issue by luke-darmanin-1** [auth0/auth0-deploy-cli#318]
### Description

The ##key## variable syntax is working as expected when performing a `deploy`. When doing a `dump` however the ##key## is replaced with the actual value. This is a problem because when we then do a `deploy` again, the string value is used as opposed to interpreted via ##key##.

My expectation would have been that the `dump` script checks the existing files and if it finds ##key##, then it leaves this field as is. This would allow the ##key## to be interpreted at runtime.

### Reproduction

This can be consistently reproduced when using the `dump` and `deploy` commands. The field this syntax is being used for is `options.client_secret` for an enterprise connection.

## Alternatively

I did put the client secret into the enterprise connection on Auth0 console directly. I then added the below for the `dump` and `deploy` commands. It works for `dump` however when doing a `deploy` it threw the following error:
 `Before creating Windows Azure Active Directory connections you must configure the client_id and client_secret settings in the dashboard.`

```
  EXCLUDED_PROPS: {
                connections: [ "options.client_secret" ]
    },
```

### Environment

Library version: 5.5.0
NodeJS: v14.15.4

### What we're trying to achieve

We're setting up an enterprise connection and wanting to keep it in source control. This all works fine via `deploy` and `dump` except for the client secret - We do not want to commit this to the repo.

**Comment by sobil** [comment]
I'm not sure making dump aware of the current state stored locally is practical.

I think this could be handled by extending: `/src/context/defaults.js` to provide secret overrides for connection params similar to `emailProviderDefaults`
