### ISSUE TITLE
npm audit: "found 5 high severity vulnerabilities" in netmask and pug dependencies

### ISSUE THREAD

**Issue by navbruce** [auth0/auth0-deploy-cli#333]
> **Please do not report security vulnerabilities here**.

Yes this is a security issue, but since it comes from `npm audit` it's not exactly a new or sensitive disclosure.

### Description

`npm audit` reports `pug` and `netmask` dependencies as having high severity vulnerabilities.

### Reproduction

`$ npm audit`

### Environment

auth0-deploy-cli version 5.5.5

**Comment by tdawgy** [comment]
Bumping this as it's tripping some of our security audit controls.

**Comment by shushen** [comment]
Thanks for reporting the issue!

We've released [v7.0.0](https://github.com/auth0/auth0-deploy-cli/releases/tag/v7.0.0), which as of today (June 14 2021) is vulnerability-free per `npm audit`.

We've also released a security fix release [v5.6.0](https://github.com/auth0/auth0-deploy-cli/releases/tag/v5.6.0) for users who's not ready for v7 yet, but we encourage everyone to upgrade to v7.x to enjoy improved security.

**Comment by navbruce** [comment]
Can you confirm that you will not deprecate v7.0.0 and force us to revert to v5.* the way you did with v6.0.0?
