### ISSUE TITLE
Deploy CLI does not work with node10

### ISSUE THREAD

**Issue by altery** [auth0/auth0-deploy-cli#335]
Affects CLI v5.5.5

According to the documentation, the CLI should run with node8 or higher. But when running the CLI on node10, zillions of identical errors are printed:

```
uncaughtException: false == true date=Tue Apr 06 2021 14:52:32 GMT+0200 (Central European Summer Time), pid=23, uid=1354, gid=1111, cwd=/workspace, execPath=/opt/node/node-v10.23.0-linux-x64/bin/node, version=v10.23.0, argv=[/opt/node/node-v10.23.0-linux-x64/bin/node, /workspace/node_modules/.bin/a0deploy, import, -c, /workspace/jenkins/pipeline-scripts/../../deployment/config/development.json, -i, /workspace/jenkins/pipeline-scripts/../../deployment], rss=82366464, heapTotal=66469888, heapUsed=29982600, external=553179, loadavg=[0.3466796875, 0.2431640625, 0.783203125], uptime=2976160, trace=[column=3, file=timers.js, function=listOnTimeout, line=270, method=null, native=false, column=10, file=timers.js, function=Timer.processTimers, line=223, method=processTimers, native=false], stack=[AssertionError [ERR_ASSERTION]: false == true,     at listOnTimeout (timers.js:270:3),     at Timer.processTimers (timers.js:223:10)]
```

It works well on node12.

**Comment by ojintoad** [comment]
We have also encountered this. I believe we *may* have a workaround where you can use `package-lock.json` file and `npm ci` to limit the versions of some dependency updates that cause this.

**Comment by ojintoad** [comment]
We've worked around this by installing the auth0 cli, using `npm ci` to install the tool and manually manipulating the package-lock.json to use an older version of this dependency:

```
"auth0-source-control-extension-tools": {
      "version": "4.4.2",
      "resolved": "https://registry.npmjs.org/auth0-source-control-extension-tools/-/auth0-source-control-extension-tools-4.4.2.tgz",
      "integrity": "sha512-kJpOvWYfjhlsoo0dRH+afJPUIych6lwNmg3lzj/0JLpGh+r+21098HWQxo6Sqi+ZWPyH48LIvoGVNGfBPsno4g==",
      "requires": {
        "ajv": "^6.5.2",
        "auth0-extension-tools": "^1.5.0",
        "babel-preset-env": "^1.7.0",
        "dot-prop": "^4.2.0",
        "lodash": "^4.17.21",
        "promise-pool-executor": "^1.1.1",
        "rimraf": "^2.5.4",
        "winston": "^2.2.0"
      },
      "dependencies": {
        "lodash": {
          "version": "4.17.21",
          "resolved": "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz",
          "integrity": "sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg=="
        }
      }
    },
```

Clearing out node_modules and then running `npm ci` with that led to an updated version that also worked, though it feels kind of bad

**Comment by stevezau** [comment]
I also found this last week. I tracked it down to this lib https://github.com/auth0-extensions/auth0-source-control-extension-tools/blob/master/package.json#L25

It is due to concurrency. https://github.com/auth0-extensions/auth0-source-control-extension-tools/blob/master/src/auth0/client.js#L6

If you change that from 3 to 1, it works.

**Comment by shushen** [comment]
Hi @altery,

Thanks for the bug report. We current testing the deploy-cli against Node.js LTS versions 8/12/14 as part of CI: https://github.com/auth0/auth0-deploy-cli/blob/a4d5f9b599c113a535017902d9cdad0476d408cf/.circleci/config.yml#L54

Node 8 support will likely be dropped soon as it's been EOL upstream. Node 10 is not a LTS version and has been EOL'd as well (please see https://nodejs.org/en/about/releases/). Therefore, I'm marking this issue as won't fix. Please consider upgrading to Node 12. Thanks!

**Comment by ojintoad** [comment]
This makes sense.

Maintainers should probably indicate in the readme/issue template their intent to only support LTS versions also.

If it's there, feel free to point out, but I'm not seeing it.

**Comment by altery** [comment]
Yes, I think it should be mentioned in the [README](https://github.com/auth0/auth0-deploy-cli/blob/master/README.md) that the CLI is only tested/supported with LTS versions. Currently, it just states

```
Node.js version 8 or later is required to run this tool since v5.0.0.
```
