### ISSUE TITLE
Provide reason for deprication Auth0 Deploy CLI extention

### ISSUE THREAD

**Issue by dmi3y** [auth0/auth0-deploy-cli#336]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

As a Auth0 customer I am seeing deprecation notice on auth0 cli extension even though I'm using the latest version.
<img width="434" alt="Cursor_and_Extensions" src="https://user-images.githubusercontent.com/1277279/113905806-6887aa80-9788-11eb-88b1-26f3253ad0e1.png">

There is no information anywhere that I can find about the reasons of this deprecation.

### Describe the ideal solution

> A clear and concise description of what you want to happen.

Would be nice to see clear documentation description about deprecation reasons, and also have any suggestions about the migration path(s) if any.

## Alternatives and current work-arounds

> A clear and concise description of any alternatives you've considered or any work-arounds that are currently in place.

### Additional context

> Add any other context or screenshots about the feature request here.

I'm also noticing deprecation note on GitHub deployment extension.

**Comment by david-blustein** [comment]
@dmi3y I believe that the manual procedure found at https://auth0.com/docs/deploy/deploy-cli-tool/create-and-configure-the-deploy-cli-application is functionally equivalent to what was previously provided by the (now) deprecated extension.

**Comment by dmi3y** [comment]
@david-blustein thanks, yes, I too think this is a reason. Github deploy likely is using same cli script under the hood.

**Comment by shushen** [comment]
Hi @dmi3y! Please kindly refer to our change log which explains our thinking behind the change: https://auth0.com/changelog#1Eee2MQt0uQsfKCL27aDi5

**Comment by dmi3y** [comment]
Thank you @shushen this explains good deal of it. I'm thinking it would be good to put it somewhere at the repo README level to make it super clear to others.
