### ISSUE TITLE
how to create / manage  new-universal-login-experience templates and customise prompt text for them in auth0-deploy-cli tool?

### ISSUE THREAD

**Issue by gawas-gautam** [auth0/auth0-deploy-cli#343]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

> I'd like to be able to create new universal login page prompts template with this CLI. Similar to the below documentation
https://auth0.com/docs/universal-login/new-experience/universal-login-page-templates
I'd like to be able to customize text for the universal login page prompts with this CLI. Similar to the below documentation
https://auth0.com/docs/universal-login/new-experience/text-customization-new-universal-login

Related to a similar requests https://github.com/auth0/auth0-deploy-cli/issues/276 and https://github.com/auth0/auth0-deploy-cli/issues/314

### Describe the ideal solution

> A clear and concise description of what you want to happen.

## Alternatives and current work-arounds

> A clear and concise description of any alternatives you've considered or any work-arounds that are currently in place.

### Additional context

> Add any other context or screenshots about the feature request here.

**Comment by kevinrs5855** [comment]
I also need this functionality, any ETA for when these new features will be supported?  @gawas-gautam , a work around for now is to just call the auth0 management API using their nodeJS sdk and then invoke the deploy-cli using a single nodejs script.

**Comment by willvedd** [comment]
Thanks for creating this issue! Universal login templates and similar configuration is certainly important and understandable why you're requesting it. However, this is a duplicate of #276 and going to defer to that ticket for future conversation.
