### ISSUE TITLE
Unable to export successfully due to emailTemplates error

### ISSUE THREAD

**Issue by rynecheow** [auth0/auth0-deploy-cli#344]
### Description

> When performing an export from my PSaaS tenant as usual, it failed at emailTemplates step with error
```
2021-05-17T03:03:46.761Z - info: Retrieving emailTemplates data from Auth0
Oh no, something went wrong. Error: Error: Problem loading tenant data from Auth0 Bad Request: Path validation error: 'Invalid value "user_invitation"' on property templateName (Template name. Can be `verify_email`, `verify_email_by_code`, `reset_email`, `welcome_email`, `blocked_account`, `stolen_credentials`, `enrollment_email`, `mfa_oob_code`, `change_password` (legacy), or `password_reset` (legacy)).
```

### Reproduction

> Consistently reproducible via "export"

> Where applicable, please include:
>
> - Code sample to reproduce the issue
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots
![Screenshot 2021-05-17 at 11 02 25 AM](https://user-images.githubusercontent.com/3182449/118427307-7ae9f200-b6ff-11eb-8b62-07ccb241e048.png)

### Environment

PSaaS tenant

> Please provide the following:

- **Version of this library used:** 5.5.1
- **Version of the platform or framework used, if applicable:** Node 12
- **Other relevant versions (language, server software, OS, browser):** 
- **Other modules/plugins/libraries that might be involved:**

**Comment by matiya** [comment]
I'm getting the same error. Also in a private tenant.

With version 5.5.5 works, but 5.5.6 does not.

**Comment by willvedd** [comment]
@rynecheow Are you still having this issue? From the error you posted it looks like the `user_invitation` property is causing the Auth0 to balk. Can you provide the relevant configuration to help us troubleshoot? Further it might be worth updating the CLI to see if that fixes your issue.

**Comment by willvedd** [comment]
Thanks for opening this issue but opting to close it because it's not actionable on our end. If this is still an active issue for folks, I invite you to create a new ticket so we can best help your specific issue.
