### ISSUE TITLE
Add support for importing/exporting Actions

### ISSUE THREAD

**Issue by grimsa** [auth0/auth0-deploy-cli#347]
### Describe the problem you'd like to have solved

Ability to export/import Actions (both Flows and Custom Actions).

### Describe the ideal solution

Auth0 Deploy CLI fully supports Action import/export, same way it supports Rules currently.

### Alternatives and current work-arounds

Using the older Rules instead of Actions.

### Additional context

![image](https://user-images.githubusercontent.com/8446128/119662590-3a465300-be3a-11eb-8ea5-e0df632da548.png)
This suggestion is misleading for projects that rely on Auth0 Deploy CLI to manage Auth0 settings.
The linked documentation also does not mention lack of Deploy CLI support as well.

**Comment by josephpage** [comment]
Actions are available in auth0-deploy-cli under the `beta` tag : `npm install -g auth0-deploy-cli@beta`
Currently the latest beta is [`6.3.2-beta.0`](https://github.com/auth0/auth0-deploy-cli/releases/tag/v6.3.2-beta.0) while current stable release is [`5.5.7`](https://github.com/auth0/auth0-deploy-cli/releases/tag/v5.5.7).

**Comment by shushen** [comment]
We've released [v7.0.0](https://github.com/auth0/auth0-deploy-cli/releases/tag/v7.0.0), which has support for Actions.

Please see also the wiki for migration notes: https://github.com/auth0/auth0-deploy-cli/wiki/Migrating#v5-to-v7 (we're updating Auth0 Docs for deploy-cli with these notes as well).
