### ISSUE TITLE
Problem running command export

### ISSUE THREAD

**Issue by NavidHamidi** [auth0/auth0-deploy-cli#348]
The deploy cli beta ran into a problem when he tried to retrieve the emails templates (I'm running behind a proxy).

![dsBuffer bmp](https://user-images.githubusercontent.com/33211965/120986766-38a35600-c77d-11eb-9862-17813ab98a25.png)

I do not where it comes because on another computer this error does not appear.

How can I fix this?

Thank you

**Comment by shushen** [comment]
Hi @NavidHamidi , this looks like a network problem in your local environment, the deploy-cli should be reaching out to our management API and it appears you might have it redirected to a local proxy, which is where the connection failed. t and I'm afraid there's not much we can help with.
