### ISSUE TITLE
Cannot import tenant, error: Schema validation failed loading

### ISSUE THREAD

**Issue by exegonmar** [auth0/auth0-deploy-cli#349]
### Description

Cannot import tenant, and i get the following error:

2021-06-09T18:33:47.464Z - error: Problem running command import
2021-06-09T18:33:47.465Z - error: Schema validation failed loading [
    {
        "keyword": "enum",
        "dataPath": ".guardianFactors[4].name",
        "schemaPath": "#/properties/guardianFactors/items/properties/name/enum",
        "params": {
            "allowedValues": [
                "sms",
                "push-notification",
                "otp",
                "email",
                "duo",
                "webauthn-roaming",
                "webauthn-platform"
            ]
        },
        "message": "should be equal to one of the allowed values"
    }
]

### Reproduction
Export configuration from existing tenant and try to reimport it into another tenant.

### Environment

Deploy CLI tool V5.5.6

**Comment by shushen** [comment]
Hi @exegonmar, the factor you are trying to import may not be supported by your tenant. Please reach out to our custom support to further troubleshoot the problem. Thanks for the report.
