### ISSUE TITLE
Unused npm dependencies in auth0-source-control-extension-tools

### ISSUE THREAD

**Issue by matthieusieben** [auth0/auth0-deploy-cli#350]
The following dependencies  are listed in `auth0-source-control-extension-tools` but look like they should be referenced as `devDependencies` instead:
 - `babel-preset-env`
 - `rimraf`

**Comment by shushen** [comment]
Hi @matthieusieben! Thanks for reporting the issue. We moved `auth0-source-control-extension-tools` into `auth0-deploy-cli` starting from v7.0.0 and should have resolved the issues as you reported.
