### ISSUE TITLE
Can't create clients

### ISSUE THREAD

**Issue by zorro2b** [auth0/auth0-deploy-cli#36]
I am trying to deploy config dumped from one tenant to a new one.
It has successfully created the rules, but when it gets to "Creating clients..." it fails with "Error: This operation must be authorized by Auth0"

I have tried creating the deploy cli client via the Auth0 Deploy CLI Extension as well as manually to ensure that all the client related grants are there but the result is the same in both cases.

**Comment by healerz** [comment]
i experience the same

**Comment by healerz** [comment]
@zorro2b i found the issue, at least in my case. I was providing the client id as well, which is forbidden. After i removed the client id from the config, it worked.
Btw, the same happens if you try to create a client directly via the management api.

**Comment by zorro2b** [comment]
@healerz ahh of course! Same for me, fixed now.
