### ISSUE TITLE
Detect incompatible tenant flags in multi-tentant contexts

### ISSUE THREAD

**Issue by Bnewman** [auth0/auth0-deploy-cli#374]
### Description

I get the following error when running `auth0 import` against a previously exported yaml tenant configuration:
`You are not allowed to set flag 'trust_azure_adfs_email_verified_connection_property' for this tenant.`

My understanding, based on a discussion with the Auth0 architect consultant working with us, is that this setting requires `updated:tenant_settings` on the Management Api, which our client application is configured to have.

### Reproduction
1. Create an Application in the target Auth0 tenant with all permissions indicated in the [documentation](https://auth0.com/docs/deploy/deploy-cli-tool/create-and-configure-the-deploy-cli-application#required-api-permissions), including 'update:tenant_settings'.
1. Run `a0deploy import` configured to use the Application created in step 1 on an exported configuration that contains `trust_azure_adfs_email_verified_connection_property: false` in the `tenant.flags` object in tenant.yaml .

#### Actual Results
- Import fails and displays the error message quoted above.

#### Expected Results
- Import succeeds 

#### Work-around
Added the following to the export configuration so it would not be included when importing:
```
    "EXCLUDED_PROPS": {
      "tenant": ["flags.trust_azure_adfs_email_verified_connection_property"]
    }
```

### Environment

- **Version of this library used: 7.2.0**

Here is a screenshot of the permissions for the Application I am using to run the import filtered on permissions containing the word 'tenant':
![image](https://user-images.githubusercontent.com/282606/131029479-ca649143-f4d7-4ba0-a260-8ffa93ae361a.png)

Here is a snippet of the configuration containing the client Id, which matches the screenshot of the dashboard above:
```
    "AUTH0_DOMAIN": "steelcase-smart-and-connected-staging.auth0.com",
    "AUTH0_CLIENT_ID": "FYnws4zcwCCQr5BBGbP38CTbbL5QcsrC",
```

**Comment by saurabh-deep** [comment]
Hello @Bnewman! Did you every find a solution for this? We are also facing the same issue with this particular flag - trust_azure_adfs_email_verified_connection_property.

It exports just fine, but can't import when this flag is present in the tenant file.

**Comment by saurabh-deep** [comment]
Turns out this flag is not available for this particular tenant where I am importing. The setting isn't available in the Advanced tab under Migrations. This flag s not available in all client. I think it's sorted.

**Comment by willvedd** [comment]
>Turns out this flag is not available for this particular tenant where I am importing. 

This is correct. The particular error originates from the Management API, not Deploy CLI. Looking at the server code, I'm able to confirm that error only occurs when a particular flag is not supported by a tenant. There are no Management API permissions that can force that flag through. 

I can only see this occurring in a multi-tenant context where, presumably, your production tenant is on an elevated tier or configured different in the backend from your lower-level environments. So when you attempt to apply tenant configuration to another tenant that's configured differently, you may experience this error.

I'm wondering what the future solution here would be. I suppose one approach would be to ignore/skip unsupported flags, but that may be at the cost of unsupported functionality elsewhere. I think we could also begin to be a bit more prescriptive with recommendations around best practices, perhaps suggesting that all tenants in your workflow are configured with the same feature flags for best experience. However, I know that users only have so much control over this.
