### ISSUE TITLE
Set Suspicious IP Throttling using auth0-deploy-cli

### ISSUE THREAD

**Issue by jcygan-nowaera** [auth0/auth0-deploy-cli#377]
Wen we use  auth0-deploy-cli to deploy project into auth0 we have no way to disable/enable setting `Security > Attack Protection > Suspicious IP Throttling`

Would be great to have this possibility to define this flag state in file tenant.json in the same way like e.g. for disable_clickjack_protection_headers in flag property

**Comment by jermeo** [comment]
hello, same thing for me.
I need a way to manage all the security features with CLI or API
It seems it's not currently possible.

**Comment by kylewernham** [comment]
Hey @klikstermkd , is there a plan to add Bot detection as part of `auth0-deploy-cli` capabilities? We've wrapped the tool for our CI/CD process and it'd be nice to persist that via export/imports.

**Comment by klikstermkd** [comment]
I don't work for Auth0, so not sure about their plans 🙂

**Comment by willvedd** [comment]
@kylewernham @klikstermkd @jermeo @jcygan-nowaera Good news folks, [7.5.0](https://github.com/auth0/auth0-deploy-cli/releases/tag/v7.5.0) has added the ability to manage the attack protection endpoints, including suspicious IP throttling. I encourage you to update and test. I'm closing this for now but please open a new ticket if you have any issues.

**Comment by rbuitragoc** [comment]
Looking forward to have support for bot-detection (CAPTCHA settings) for auth0 CLI as well. Is this support planned as well? I see the question raised https://github.com/auth0/auth0-deploy-cli/issues/546, can it be a feature request?

**Comment by pinkfloydx33** [comment]
Looking for the same. At present we make these management api calls in our CI scripts immediately after a0deploy. Would be great to not have to manage seperately.
