### ISSUE TITLE
Skip validation for credential info when emailProvider.enabled is false

### ISSUE THREAD

**Issue by hayashi-ay** [auth0/auth0-deploy-cli#384]
### Describe the problem you'd like to have solved

The cli checks `credentials.accessKeyId` and `credentials.secretAccessKey` even though `emailProvider.enabled` is false when importing.

In this case, even though these values are not needed, the following error is shown.

> error: Payload validation error: 'None of the valid schemas were met' on property credentials (Credentials required to use the provider). Inner errors: [ Payload validation error: 'Additional properties not allowed: region,secretAccessKey,accessKeyId' on property credentials ({description}). (also) Payload validation error: 'String is too short (0 chars), minimum 1' on property credentials.accessKeyId (AWS Access Key ID). (also) Payload validation error: 'String is too short (0 chars), minimum 1' on property credentials.secretAccessKey (AWS Secret Access Key). (also) Payload validation error: 'Additional properties not allowed: secretAccessKey,accessKeyId' on property credentials ({description}). ].

### Describe the ideal solution
Just skipping a validation when `emailProvider.enabled` is false.

## Alternatives and current work-arounds

Passing dummy values.

**Comment by willvedd** [comment]
I'm not sure if this is still an active irritation, but I have looked at this quite a few times. I believe these values are forced into the payload with [this block of code](https://github.com/auth0/auth0-deploy-cli/blob/7a15ecacb97d5cd74542c3f3f9c22ee78bec149d/src/context/defaults.ts#L27):

```ts
  if (name === 'ses') {
    updated.credentials = {
      accessKeyId: '##SES_ACCESS_KEY_ID##',
      secretAccessKey: '##SES_ACCESS_SECRET_KEY##',
      region: '##SES_AWS_REGION##',
      ...(updated.credentials || {}),
    };
  }
```

So it _only_ targets SES email providers, but you're correct that it adds those secret values regardless of status. 

I'm tempted to add a conditional here for activity status and if disabled, omit the secrets. A side effect here is that you could theoretically want to adjust these values while an email provider is disabled. I'd need to add a number of other conditional checks to prevent those cases. Additionally, I think there is a possibility that the `accessKeyId` and `secretAccessKey` are required by the Management API for any PATCH operation. Lastly, the idea of `emailProviderDefaults` has always been a confusing one that has haunted us a bit, but it's there and likely that folks are still reliant on that functionality. 

All of this to say that it's not as straightforward of a feature as it may seem. Especially given the lack of activity on this thread, the payoff just doesn't seem worth it right now. While not elegant, I think it's fine to use placeholder values as a workaround. 

As this project starts to resolve some of its identity issues, we can better define the flexibility of this tool. Once we do, feature requests like this will be a less ambiguous as to wether it's a bug or a feature request. 

But for now, I'm opting to close this. Our team is small and we need to be decisive about prioritizing our time and there are just so many other feature requests that have a larger impact than this one.
