### ISSUE TITLE
Deploy CLI Required API permissions

### ISSUE THREAD

**Issue by zanebclark** [auth0/auth0-deploy-cli#390]
### Description

The required api permissions defined [here](https://auth0.com/docs/deploy/deploy-cli-tool/create-and-configure-the-deploy-cli-application#required-api-permissions) don't call for read:organizations. This results in an error for certain tenants. I'd like to see the list of required apis updated to include the appropriate organization permissions

**Comment by shushen** [comment]
Thanks for your report. The documentation has been updated to include `read:organizations`.
