### ISSUE TITLE
Ability to exclude objects when import/export using deploy-cli

### ISSUE THREAD

**Issue by locscoutbee** [auth0/auth0-deploy-cli#394]
### Describe the problem you'd like to have solved

I am having around 10k organizations in auth0 tenant. Using deploy-cli import will be very slow. I just want to update manually on Auth0 Console only for this case.

### Describe the ideal solution

The ability to exclude organizations when import or export by adding a settings in config.json

**Comment by willvedd** [comment]
Thanks for opening this issue, it's definitely a reasonable feature to ask for. As I have [mentioned in another thread](https://github.com/auth0/auth0-deploy-cli/issues/375#issuecomment-1063118338), resources exclusion should be a first-class feature and I'd like to take this opportunity to create a more holistic approach. It's on our roadmap so keep an eye out for it in the future!

**Comment by willvedd** [comment]
@locscoutbee I've raised a [proposal for resource exclusion](https://github.com/auth0/auth0-deploy-cli/issues/451) that may solve this issue. It would be great to receive your feedback since your use case relies upon excluding organizations.

**Comment by locscoutbee** [comment]
Thank you @willvedd for your nice proposal! I could not agree more. I am looking forward to seeing this new feature.

**Comment by willvedd** [comment]
Following up here, as proposed in the above-mentioned resource exclusion RFC, the `AUTH0_EXCLUDED` configuration property has been added in the 7.7.0 release. It will work bi-directionally and should solve your use case. Example:

```json
{ 
 "AUTH0_DOMAIN": "<YOUR_DOMAIN>", 
 "AUTH0_CLIENT_ID": "<YOUR_CLIENT_ID>", 
 "AUTH0_CLIENT_SECRET": "<YOUR_CLIENT_SECRET>", 
 "AUTH0_EXCLUDED": [ "organizations"] 
 }
 ```
 
Please update and give it a go! In the meantime, I'm opting to close this out but feel free to re-open if needed.
