### ISSUE TITLE
https://github.com/auth0/auth0-deploy-cli#troubleshooting is missing

### ISSUE THREAD

**Issue by hayashi-ay** [auth0/auth0-deploy-cli#396]
### Description
The cli show an info message attached below when something wrong with imported yaml settings but the link is missing from README.md.

```
info: Please see https://github.com/auth0/auth0-deploy-cli#troubleshooting for common issues
```
<img width="1116" alt="スクリーンショット 2022-01-17 14 50 13" src="https://user-images.githubusercontent.com/39038230/149714800-2228a9b2-3c6f-409c-9b1c-3c489b23fc9f.png">

### Reproduction
Run the cli with wrong settings such as missing the `from` property from `emailTemplates.template`.

### Environment
```
$ a0deploy --version
7.3.2
```

**Comment by willvedd** [comment]
That dead link has been replaced with a more appropriate one in our [v7.5.1 release](https://github.com/auth0/auth0-deploy-cli/releases/tag/v7.5.1). Thanks for opening!
