### ISSUE TITLE
Add config to exclude Actions - AUTH0_EXCLUDED_ACTIONS

### ISSUE THREAD

**Issue by MGough** [auth0/auth0-deploy-cli#397]
### Describe the problem you'd like to have solved

Auth0 is pushing a move from Rules to Actions, but there's no way to exclude actions from being imported/exported using the Deploy CLI

### Describe the ideal solution

Similar to the `AUTH0_EXCLUDED_RULES` there should be a `AUTH0_EXCLUDED_ACTIONS` config value.

## Alternatives and current work-arounds

Continuing to use Auth0 Rules instead of actions

### Additional context
Other example of 'exclude' configs exist, but actions is missing: https://auth0.com/docs/deploy-monitor/deploy-cli-tool/import-export-tenant-configuration-to-yaml-file#example-configuration-file

**Comment by willvedd** [comment]
@MGough I've raised a [proposal for excluding resources](https://github.com/auth0/auth0-deploy-cli/issues/451) that may solve this issue. It would be great to receive your feedback since your use case relies upon excluding certain resources.

**Comment by MGough** [comment]
> @MGough I've raised a [proposal for excluding resources](https://github.com/auth0/auth0-deploy-cli/issues/451) that may solve this issue. It would be great to receive your feedback since your use case relies upon excluding certain resources.

Thanks for letting me know @willvedd I'll try to take a look and leave a comment or a reaction once I've had a think, although it might not be until the end of this week.

I've found actions to be a bit of an anomaly in terms of how to exclude them (due to the action & trigger being separate) so I might have some comments or clarifications.

**Comment by charliearaya** [comment]
Shouldn't this be closed since we have this ongoing? https://github.com/auth0/auth0-deploy-cli/issues/451
