### ISSUE TITLE
Could  Deployment CLI support --dryrun option?

### ISSUE THREAD

**Issue by superff** [auth0/auth0-deploy-cli#399]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

we are currently using the auth0 deployment cli for our CD pipeline, we want to have a CI stage that can test the variables formats before running them

### Describe the ideal solution

Could `a0deploy` have a `--dryrun` option that can scan the variables but not apply the changes?

## Alternatives and current work-arounds

no workaround, we saw the errors of variables at the deployment 

### Additional context

N/A

**Comment by hayashi-ay** [comment]
There is no equivalent to `dry-run` though many developers including me want for a long time.

https://github.com/auth0/auth0-deploy-cli/issues/70

**Comment by willvedd** [comment]
Thanks for bumping this suggestion up, it's certainly reasonable to request a configuration tool to provide a terraform-esque diffing capability. However, this is a duplicate of #70 and will defer to that ticket for all further discussion.
