### ISSUE TITLE
Version 5.0.0 fails on directory import when processing databases (Problem running command import during stage processChanges when processing type databases)

### ISSUE THREAD

**Issue by itsvikasgupta** [auth0/auth0-deploy-cli#411]
Description

On running a directory import with a directory that used to work with v5, we get a failure with the following error:

```
Created [clients]: {"name":"hidden","client_id":"RlCgoLiy4mKlEHDfjVXfHOzqv3VavNdn"}
Detected the following databases should be deleted. Doing so may be destructive.  You can enable deletes by setting 'AUTH0_ALLOW_DELETE' to true in the config {"name":"Username-Password-Authentication","id":"con_XXulJ3IoKuSJyCAQ"}

Problem running command import during stage processChanges when processing type databases
Cannot read property 'resource' of undefined
```

Our directory only includes 

```
clients
connections
emails
hooks
resource-servers
conf.json
database-connections
grants
pages
rules
```

Allow deletes is turned off.

Environment

Using version 5.0.0.

**Comment by itsvikasgupta** [comment]
Is there a quick workaround to bypass the error and let it continue despite the error? Thank you.

**Comment by willvedd** [comment]
My initial hunch is that this is related to a change in the node Auth0 SDK that broke the mechanism for managing databases. You may be able to confirm this if your `auth0` npm module is running a version greater than 2.37.0. You have two options for workarounds: update to the latest version of this package (7.3.7) which pins the Auth0 node SDK or alternatively, you can pin the auth0 npm module to 2.37.0 yourself.

**Comment by willvedd** [comment]
@itsvikasgupta Thanks for opening this ticket. Unfortunately, it is a known issue that versions 2.38.0+ of the node Auth0 SDK introduce an incompatible requesting mechanism. For that reason, we offer two recommendations, the first is to update to the latest version of the deploy CLI, and secondly, if you're relying on an older version of the deploy CLI, you'll need to pin `auth0-node` to 2.37.0. 

Apologies to anyone who this inconveniences. I'm considering this issue sufficiently addressed.
