### ISSUE TITLE
Issue with exporting/importing actions

### ISSUE THREAD

**Issue by qpaack** [auth0/auth0-deploy-cli#439]
### Description

When doing an export from Auth0 with the a0deploy tool, all the actions are saved in two files with the same name:
- <action_name>/code.js -> a folder is created with the action name, storing inside the code of that action
- <action_name>.json -> a json file contains the configuration details of that action, including the code path to the code.js file of the action

The <action_name>.json file stores the path, e.g. "code": "<tenant_name>/actions/<action_name>/code.js".

The issue comes with the fact that the <tenant_name> is not something that should be added in the path, as when a0deploy is looking for the files, it is already looking in the root folder for that path, which contains directly the "actions" folder. The <tenant_name> is an extra piece of string that makes the path non-existant, giving the error:

2022-03-10T14:14:08.903Z - info: Processing directory
2022-03-10T14:14:08.982Z - error: Problem running command import
2022-03-10T14:14:08.982Z - error: Unable to load file /user/Desktop/auth0-deploy/<tenant_name>/actions/test/code.js due to Error: ENOENT: no such file or directory, access '/user/Desktop/auth0-deploy/<tenant_name>/actions/test/code.js'

This makes that, either you change manually all of the code paths, deleting the <tenant_name> from the path (something that you'll have to do for each export repository you create), or delete the actions folder, which will get rid of any path errors.

### Reproduction
To reproduce the error:
> Create some action in the tenant.
> a0deploy export --config_file config-playground.json --format directory --output_folder folder
> cd folder
> a0deploy import --config_file ../config-playground.json -input .

To manually fix the error:
> Go to folder/actions/<action_name>.js
> Delete the <tenant_name> from the "code" path variable
> rerun "a0deploy import --config_file ../config-playground.json -input ."

### Environment

> Please provide the following:

- **Version of this library used:** a0deploy 7.4.0 -> this error was already existing in previous versions
- **Other relevant versions (language, server software, OS, browser):** OS X Monterrey 12.2.1

**Comment by qpaack** [comment]
Hi @stuarthadfieldglobality,

Thanks for your reply.

When doing the import, as I added on the reproduction part, I first change directory inside of the folder itself, thus doing the "." to select the current directory instead of doing it from the parent folder. The reason why I do it like that, is because doing it from the parent folder, for some reason, a0deploy tells me "Import Successful" without actually doing anything:

```
From Parent Folder:
a0deploy import --config_file config-playground.json -input-file ./tenant_folder
2022-03-10T15:43:02.830Z - info: Processing directory
2022-03-10T15:43:02.833Z - info: Getting access token for xxxxxxxxxxxxxxxxxxxxxxx/tenant.auth0.com
2022-03-10T15:43:02.888Z - info: Import Successful
````

```
From Child Folder (tenant folder with the data):
a0deploy import --config_file ../config-playground.json -input-file .
2022-03-10T15:44:40.672Z - info: Processing directory
2022-03-10T15:44:40.745Z - error: Problem running command import
2022-03-10T15:44:40.745Z - error: Unable to load file /Users/user/Desktop/auth0-deploy/tenant_folder/auth0-tenant-test/actions/add_token_app_metadata/code.js due to Error: ENOENT: no such file or directory, access '/Users/user/Desktop/auth0-deploy/tenant_folder/auth0-tenant-test/actions/add_token_app_metadata/code.js'
```

Being "auth0-tenant-test" my tenant name, that is included in the path of the "code" variable at "actions/add_token_app_metadata.json"

I am not seeing any difference from my side either choosing the --input-file or the --input flags, both have the same output for me.

**Comment by stuarthadfieldglobality** [comment]
It should be `--input_file` not `--input-file`.

**Comment by willvedd** [comment]
@stuarthadfieldglobality Thanks for digging into this a bit.

I too am curious why it's appearing to default the directory to the tenant name. For what it's worth, I'm unable to recreate, even with the missing parameters. But I do know that the Deploy CLI sources configuration from your environment variables by default so if you had lingering config stored in an env var, perhaps even a coincidental collision, that _may_ have caused this behavior. Is it possible that the tenant name just so happens to be the same as your output folder? Otherwise I don't see anything in the code that sources the tenant name for any file-naming purposes.

It seems like the original issue has been solved, correct? Or do you folks feel like there is an actionable takeaway from this discussion? Happy to keep open if so, but prefer to close otherwise.

**Comment by qpaack** [comment]
Hi @willvedd,

Indeed, the original issue has been solved, I'll close this issue.

Regarding the part of the coincidence of the "tenant name" happening to be the same as the "output folder", that is not the case (I moved"sandbox" tenant configuration into "playground" folder, and then applied import directly to playground tenant, which it already breaks in some resources as the client grants for `Auth0 Management API` due to the tenant name being hardcoded), and thats why I was expecting it to crash a0deploy on the import. 
It could well be as you mentioned though, that a0deploy is ignoring the tenant name and taking the `AUTH0_DOMAIN` variable from the config file, which kind of makes me feel that then adding the tenant name to the "code" path variable is not being used at all, but its not affecting the import :)
