### ISSUE TITLE
Internal Server Error when importing connection

### ISSUE THREAD

**Issue by duane9** [auth0/auth0-deploy-cli#448]
### Description

`AUTH0_TENANT_NAME=... AUTH0_DOMAIN=... AUTH0_CLIENT_ID=... AUTH0_CLIENT_SECRET=... a0deploy import -i sso-configuration/uat
`

Resulting error:
```
error: Problem running command import during stage processChanges when processing type connections
error: Problem updating connections {"name":"...","id":"..."}
Internal Server Error: An internal server error occurred
```

### Reproduction

Connection:
```
{
  "options": {
    "debug": true,
    "expires": "2035-04-19T16:44:14.000Z",
    "subject": {
      "commonName": "..."
    },
    "fieldsMap": {},
    "signingCert": "...",
    "signing_key": {
      "key": "...",
      "cert": "..."
    },
    "decryptionKey": {
      "key": "...",
      "cert": "..."
    },
    "signInEndpoint": "...",
    "digestAlgorithm": "sha256",
    "protocolBinding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST",
    "signSAMLRequest": true,
    "user_id_attribute": "NameID",
    "signatureAlgorithm": "rsa-sha256",
    "set_user_root_attributes": "on_first_login"
  },
  "strategy": "samlp",
  "name": "...",
  "is_domain_connection": false,
  "show_as_button": false,
  "enabled_clients": [...]
}
```

Deploy: `AUTH0_TENANT_NAME=... AUTH0_DOMAIN=... AUTH0_CLIENT_ID=... AUTH0_CLIENT_SECRET=... a0deploy import -i sso-configuration/uat
`

The deployment halts with the internal server error. Strangely, I've found that if I delete the `decryptionKey` block from the connection JSON, it works.

### Environment

> Please provide the following:

- **Version of this library used:** 7.5.2

**Comment by willvedd** [comment]
@duane9 thanks for opening this. This appears to be some type of validation issue with the upstream services that handle SAMLP connections. For whatever reason, the GET request will return `decryptionKey` but will reject if provided with the PATCH. I'm a bit surprised that this just popped up, it'll require a bit of investigation to understand if this is some type of regression or something. 

In the meantime, you may be able to exclude that property using the `EXCLUDED_PROPS` property in your config .json file:

```json
{
  ...,
  "EXCLUDED_PROPS": {
        "connections": [
            "options. decryptionKey"
        ]
    }
}
```

Excluding the `decryptionKey` from the purview of management _should_ quell that error.

**Comment by duane9** [comment]
@willvedd, unfortunately the workaround didn't work. I still get the error. Do you know when this will be fixed? It is blocking deployments to our UAT tenant.
