### ISSUE TITLE
Dealing with the client "Bad Request: Invalid grant types" error on import

### ISSUE THREAD

**Issue by twistedstream** [auth0/auth0-deploy-cli#45]
(We should maybe move the content issue to a Troubleshooting section in the README)

## Problem

It's possible that you have an Auth0 tenant that was created before **8 June, 2017**. If so, it will likely contain clients (apps) with legacy [grant types](https://auth0.com/docs/applications/application-grant-types#grant-types-available). If you use the `a0deploy` CLI to `export` those clients and then later perform an `import`, you may see an error message that looks like this:

```shell
2018-10-28T17:16:03.341Z - error: Problem running command import during stage processChanges when processing type clients
2018-10-28T17:16:03.341Z - error: Problem updating clients {"name":"your-app","client_id":"YOUR_APP_CLIENT_ID"}
Bad Request: Invalid grant types: http://auth0.com/oauth/legacy/grant-type/ro, http://auth0.com/oauth/legacy/grant-type/ro/jwt-bearer, http://auth0.com/oauth/legacy/grant-type/delegation/refresh_token, http://auth0.com/oauth/legacy/grant-type/delegation/id_token, http://auth0.com/oauth/legacy/grant-type/access_token
```

FYI: your error may only contain some of the legacy grant types shown in the above error.

## Resolution

There are two ways to resolve this issue:

If you don't need those legacy grant types or you can [switch to a more secure alternative to their use](https://auth0.com/docs/applications/application-grant-types#secure-alternatives-to-the-legacy-grant-types), then you can simply remove them from the local client configuration file (client JSON file or section in the `tenant.yaml` file). Then try the import again.

If it turns out you do need to use at least some of these legacy grant types, then you'll need to enable their use in your tenant settings. The three tenant settings that are associated with the legacy grant types are the following (tenant > Settings > Advanced > Migrations section):
![image](https://user-images.githubusercontent.com/3535918/47619966-69458e00-dab2-11e8-93ce-46463058533e.png)
Only enable the setting(s) you actually need if you only need a subset of the grant types.

### NOTE: 
If you don't see those settings in your tenant, it's because it was created _after_ 8 June, 2017 and, therefore, you shouldn't be having this issue in the first place.

**Comment by stevezau** [comment]
Thanks @twistedstream. Will get this closed as it's a manual fix for older tenants. Others can follow your guide if they hit this issue.
