### ISSUE TITLE
Add an option to disable colors in the output

### ISSUE THREAD

**Issue by miyagi-do** [auth0/auth0-deploy-cli#460]
### Describe the problem you'd like to have solved

While using the auth0-deploy-cli import command, I was wondering if we could have an option to disable colors from the output like we do in the auth0-cli (--no-color) as mentioned in https://github.com/auth0/auth0-cli/blob/main/docs/index.md

We have a tool that does not work well with colored text, so when we run the import command on it, the colored text does not render properly (see the text around `info` and `warn` in the `Output` below):

Import Command
```
a0deploy import --config_file import-config.json --input_file tenant_entities
```

Output
```
2022-03-28T18:14:40.458Z - [32minfo[39m: Processing directory entities
2022-03-28T18:14:41.004Z - [33mwarn[39m: Detected that the client_metadata of the following undefined should be emptied. Doing so may be destructive.
You can enable deletes by setting 'AUTH0_ALLOW_DELETE' to true in the config
.....
.....        

2022-03-28T18:14:41.385Z - [32minfo[39m: Import Successful
```

### Describe the ideal solution

Add an optional `--no-color` to `auth0-deploy-cli`, to give users an option to display the output without colors.

**Comment by willvedd** [comment]
@miyagi-do Thanks for opening and definitely appreciate the suggestion, I've added it to our product backlog. While a `--no-color` option is certainly a good idea, I don't see us getting to it anytime soon, we have several other initiatives we'd like to address first. 

However, you should be able to strip the colors by piping into the `sed` command using something like the following ([credit](https://stackoverflow.com/a/18000433)):

```shell
a0deploy import -c=config.json --input_file=local/tenant.yaml | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g"
```

While not the most elegant solution, the above workaround should solve your pain point.
