### ISSUE TITLE
attackProtection Not found error when exporting config from private cloud

### ISSUE THREAD

**Issue by ChatLurking** [auth0/auth0-deploy-cli#486]
### Description

When attempting to export with `a0deploy@7.7.1` I get the error: 
```
error: Problem running command export during stage load when processing type attackProtection
error: Not Found
```
Downgrading to `a0deploy@7.3.1` did not fail the export, but `attackProtection` is not exported.

### Reproduction

run `a0deploy export --config_file config/private-staging.json --format directory --output_folder private-staging`

![CleanShot 2022-04-11 at 22 41 03](https://user-images.githubusercontent.com/10388044/162888736-4b8c5d47-1b82-4a1c-b194-3cb07e76f487.png)

### Environment

> Please provide the following:

- **Version of this library used:** 7.71, but happens with 7.5.0 and above
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):** OSX - intel chip
- **Other modules/plugins/libraries that might be involved:** Auth0 Private Cloud

**Comment by willvedd** [comment]
@ChatLurking Thanks for submitting this issue. Private cloud sometimes has slightly different Management API feature offerings. My hunch here is that attack protection has not been enabled for your private cloud tenant. Can you reiterate your intentions? Are you looking to manage attack protection with the deploy CLI or were you just looking to update to the most current version. 

In the meantime, you can exclude attack protection from the purview of management by adding the following configuration to your `config/private-staging.json` file:  `"AUTH0_EXCLUDED": [ "attackProtection"]`.

**Comment by willvedd** [comment]
@ChatLurking Sorry for the delay on revisiting this. Do you know if this is still an issues that's impacting your private cloud tenant? If so, it might be helpful for you to run with debug mode enabled with the `--debug` flag to hopefully provide more information on this issue.

**Comment by ChatLurking** [comment]
@willvedd It probably is still an issue - we moved away from using this to the terraform module. 

I can check to see if it is still and issue and run debug in the next few days.

**Comment by willvedd** [comment]
My best guess is that for private cloud tenants, specific attack protection endpoints do not exist. While I'm sure this issue is legitimate, there is not enough debugging information here for us to address at this time. Closing until more details emerge.
