### ISSUE TITLE
Respect AUTH0_KEYWORD_REPLACE_MAPPINGS defined inside of AUTH0_KEYWORD_REPLACE_MAPPINGS

### ISSUE THREAD

**Issue by zanebclark** [auth0/auth0-deploy-cli#487]
### Describe the problem you'd like to have solved

I'd like to be able to define `credentials` in my `emails/provider.json` template file that can accommodate my development environment and my production environment. My development environment uses an smtp integration: 
```json
{
      "smtp_host": "someserver",
      "smtp_port": 2525,
      "smtp_user": "someusername",
      "smtp_pass": "##SOME_PASSWORD##"
}
```

My production environment is configured with SendGrid: 
```json
{
      "api_key": "##SENDGRID_API_KEY##"
}
```

If I define my template `credentials` as:
```
{
      "smtp_host": "someserver",
      "smtp_port": 2525,
      "smtp_user": "someusername",
      "smtp_pass": "##SOME_PASSWORD##"
      "api_key": "##SENDGRID_API_KEY##"
}
```

I receive errors complaining about the presence of some of the keys I don't need for one configuration or the other. I've taken to defining email credentials as a `AUTH0_KEYWORD_REPLACE_MAPPINGS` value and passing the entire JSON into the template: 
```json
{
  "enabled": true,
  "credentials": @@EMAIL_CREDENTIALS@@,
  "name": "##EMAIL_PROVIDER_NAME##",
  "default_from_address": "##EMAIL_FROM##"
}
```

Using this approach, I can use the required keys for the right environment. Here's the problem: Environment variable substitutions in the config.json file aren't respected. 

```json
{
  "AUTH0_KEYWORD_REPLACE_MAPPINGS": {
    "EMAIL_CREDENTIALS": {
      "smtp_pass": "##MAILTRAP_PASSWORD##"
    }
  }
}
```

### Describe the ideal solution

Apply environment variable substitution after substituting `@@AUTH0_KEYWORD_REPLACE_MAPPINGS@@` values so that `##AUTH0_KEYWORD_REPLACE_MAPPINGS##` inside `@@AUTH0_KEYWORD_REPLACE_MAPPINGS@@` are respected

## Alternatives and current work-arounds

Load the JSON and use reviver to swap out environment variables. Pass this object into `deploy` or `dump` as `config` (vs. `config_file`)

```typescript
  // Support Environment Variable substitution within config.json files
  let configString = fs.readFileSync(config_file, { encoding: "utf8", flag: "r" });
  if (configString.charCodeAt(0) === 0xfeff) {
    configString = configString.slice(1);
  }
  // Mirror format of Environment Variable substitution in tenantConfig files: ##ENV_VAR## => ENV_VAR
  return JSON.parse(configString, (_, value) => {
    if (typeof value === "string" && value.slice(2, -2) in process.env) {
      return process.env[value.slice(2, -2)];
    }
    return value;
  });
```

**Comment by willvedd** [comment]
So to summarize, you're requesting the ability for the ## string replacement to work within an @@ array replacement (understand you're using for objects, but the intention is for arrays)? So suppose you had the following example, albeit a bit contrived:

**Config.json**
```json
{
  "AUTH0_KEYWORD_REPLACE_MAPPINGS": {
    "MAILTRAP_PASSWORD": "your-mailtrip-password",
    "EMAIL_CREDENTIALS": {
      "smtp_pass": "##MAILTRAP_PASSWORD##"
    }
  }
}
```
**mock-email-config.json**:
```json
{
  email-prop-1: "foo",
  email-mailtrap-pass: "##MAILTRAP_PASSWORD##",
  email-credentials: "@@EMAIL_CREDENTIALS@@"
}
```

You would expect the following output:
```json
{
  email-prop-1: "foo",
  email-mailtrap-pass: "your-mailtrip-password",
  email-credentials: {
    "smtp_pass": "your-mailtrip-password"
  }
}
```

If so, while I don't fully understand the usecase, at the surface, that seems like a fairly reasonable expectation. And assuming that my understanding is correct, I don't believe it to be a heavy lift. In fact, I was able to whip up a test case for the above and it passes. Originally, the @@ replacement syntax was meant for arrays, but no technical reason why it couldn't work for objects. I think I'd like to draw the line somewhere in terms of complexity though, this use case is fine, but pushing beyond this requirement could get us into gnarly edge-case territory.

**Comment by zanebclark** [comment]
@willvedd , you've captured the ask. As for the usecase, perhaps I should be asking for guidance rather than a feature. If I need different keys in an object across different tenants, what's the best way to handle that? For example, my production email credentials 
```
    "credentials": {
      "api_key": "##SENDGRID_API_KEY##"
    },
```
and my development email credentials: 
```
{
      "smtp_host": "smtp.mailtrap.io",
      "smtp_port": 0000,
      "smtp_user": "someuser",
      "smtp_pass": "##MAILTRAP_PASSWORD##"
    }
```

Sending a superset of the keys results in this error: 
```
Error: dev-atmts push failed. <%= "Error: Bad Request: Payload validation error: 'None of the valid schemas were met' on property credentials (Credentials required to use the provider). Inner errors: [ Payload validation error: 'Additional properties not allowed: smtp_pass,smtp_user,smtp_port,smtp_host' on property credentials ({description}). (also) Payload validation error: 'Additional properties not allowed: api_key,smtp_pass,smtp_user,smtp_port,smtp_host' on property credentials ({description}). (also) Payload validation error: 'Additional properties not allowed: api_key' on property credentials ({description}). ]." %>
```

I wonder how users are currently managing such a situation?

**Comment by willvedd** [comment]
Understood. This tool assumes that the same sets of config would apply across different tentants, and as you've found, the Management API tends to be fairly strict with not allowing extraneous fields. In your case, because your email integration requires a different payload depending on the environment, I believe your inclination to leverage keyword replacement to be sensible. I don't have any alternative workarounds so it makes sense to add that functionality IMO.

In the `keywordReplace` function, I believe the `keywordArrayReplace` and `keywordStringReplace` operations need to swap order, or at least that's what ultimately satisfied my test case. If you feel comfortable hacking the compiled source to test, I'd be curious to see if it satisfies your needs for the time being. In the meantime, I'll throw up a PR and try to have it released sometime next week.
