### ISSUE TITLE
EXCLUDED_PROPS behavior improperly documented

### ISSUE THREAD

**Issue by zanebclark** [auth0/auth0-deploy-cli#488]
### Description

If you include a value in `EXCLUDED_PROPS` to avoid exposing a secret: 
```json
  "EXCLUDED_PROPS": {
    "connections": [
      "options.twilio_token"
    ]
  }
```

That value isn't returned during an export, but it is also ignored during an import.

According to the [documentation](https://auth0.com/docs/deploy-monitor/deploy-cli-tool)
> EXCLUDED_PROPS: Provides ability to exclude any unwanted properties from exported objects

This is inaccurate, as it also excludes properties from import. It's particularly hard to debug, as obfuscating the key means that there's no feedback on the state of the secret unless you remove the value from `EXCLUDED_PROPS`, at which point the value will be respected upon import. 

### Reproduction

Reproduction steps above

### Environment

a0deploy --version == 7.7.1

**Comment by willvedd** [comment]
Want to let you know that this hasn't been forgotten. I'm just now getting around to overhauling this project's documentation. The `EXCLUDED_PROPS` config property in particular has been the source of curiosity, myself included. So I'm going to make sure it gets clarified. Thanks for the feedback and stay tuned.

**Comment by willvedd** [comment]
Just merged in documentation for this project including a [slightly altered definition of `EXCLUDED_PROPS`](https://github.com/auth0/auth0-deploy-cli/blob/master/docs/configuring-the-deploy-cli.md#excluded_props). If anyone feels like this definition is incomplete or unclear, please create a PR with an alternative.
