### ISSUE TITLE
Organization Connections - Rate Limit Exceeded

### ISSUE THREAD

**Issue by ShaunInIdaho** [auth0/auth0-deploy-cli#500]
When running A0Deploy Export I am receiving a rate limit log entry for Global per minute organization_connections_read group.  My understanding is that the this tool is self limiting so that rate limits are not exceeded.  Is that correct?

I wonder if this is a bug with the new support for Organizations?  You may not experience this issue until you have 100s of Organizations in a tenant.

Full Error Message:
{
  "data.client_id": "wtl1FsWlipfAd23fRu7dxM1M6xgmSd4j",
  "data.client_name": "",
  "data.date": "2022-04-14T14:55:13.128Z",
  "data.description": "Global per minute organization_connections_read group limit has been reached",
  "data.details.request.method": "get",
  "data.details.request.path": "/api/v2/organizations/{id}/enabled_connections",
  "data.log_id": "90020220414145517395922878730454503034169518883510157314",
  "data.type": "api_limit",
  "index": 2,
  "log_id": "90020220414145517395922878730454503034169518883510157314",
  "newrelic.source": "api.logs",
  "timestamp": 1649948133241
}

**Comment by wasabii** [comment]
I'm hitting this too, now, but on every deployment I'm doing. All of which worked a week ago. No changes since then. I feel like the server-side rate limit has changed, and the tool's speed is now out of date.

Proposal: Somebody should make the rate limit configurable in an argument, or ENV variable.

**Comment by willvedd** [comment]
Am I correct in understanding that the concern here is about the rate limit _log entries_? The tool is still able to operate like normal, correct?

**Comment by wasabii** [comment]
No. The tool fails. As of a couple days ago, for every client I have that uses it (two).

It actually hits the rate limit.

**Comment by wasabii** [comment]
No. The tool fails. As of a couple days ago, for every client I have that uses it (two).

It actually hits the rate limit.

**Comment by willvedd** [comment]
Happy to look into it a bit more but would need more information for it to be actionable. Primarily:

- Relevant error message
- Version of the tool you're using
- Tenant tier: free, paid, enterprise
- Affected resource types
- How many of the affected resource types you're managing

The thing is, the underlying Node SDK that's being leveraged _does_ indeed have a rate-limiting handler that implements infinite backoff. Meaning, it's expected for these errors to occur but that they're almost definitely swallowed by the SDK and never bubbled up to the Deploy CLI. In fact, I've tried to recreate this exact issue many times and while I see rate limit errors in the logs, they're never present in the tool's output. Not to say that it's impossible, but I just need more information to make this into an actionable request.

**Comment by willvedd** [comment]
Looping back here, it is normal to be seeing API rate-limit errors in the logs as the underlying SDK relies upon those errors to self-regulate. This is especially true for free-tiered tenants which will run up against those limits much earlier. It is not normal however for those errors to interfere with the operation of the tool as the exponential backoff retry strategy should allow for the vast majority of most use cases to work. Further, I've seen no evidence of this occurring in the wild. 

For these reasons, I don't see this issue as actionable.

**Comment by arash-qc** [comment]
@willvedd A more standard/normal behavior would be having an optional delay as a config parameter in the client to avoid hitting rate-limit in the first place
