### ISSUE TITLE
From address cannot be set without an enabled email provider.

### ISSUE THREAD

**Issue by stevezau** [auth0/auth0-deploy-cli#51]
Error if deploying email templates as provider not set first.

```{"statusCode":400,"error":"Bad Request","message":"From address cannot be set without an enabled email provider."}```

**Comment by fyockm** [comment]
Fixed by https://github.com/auth0-extensions/auth0-source-control-extension-tools/pull/48
Published as `auth0-deploy-cli@2.0.6`
