### ISSUE TITLE
AUTH0_EXCLUDED isn't respect during import

### ISSUE THREAD

**Issue by DanPatten** [auth0/auth0-deploy-cli#536]
I am running auth0-cli version 7.12 and included the following:

"AUTH0_EXCLUDED": [ "customDomains" ]
The export works fine and does not include the custom-domains.json file but when importing I get the following error:

Error: <%= "Error: Error: Error parsing JSON from metadata file: tenants\zz\custom-domains\custom-domains.json, because: Unable to load file \zz\custom-domains\custom-domains.json due to Error: ENOENT: no such file or directory, access 'zz\custom-domains\custom-domains.json'" %>

Am I missing something or is this an issue?

**Comment by willvedd** [comment]
Thanks for opening this issue. I was able to recreate the issue and it appears to occur if you have an empty `customDomains` directory in your local configuration directory, regardless of how `AUTH0_EXCLUDED` is set.

So to unblock you in the short term, I advise to just delete the `custom-domains` directory. 

However, this shows that the `AUTH0_EXCLUDED` functionality doesn't apply appropriately during import. Looking at the code again, I think my thinking was that any configuration that was ignored on export would lack configuration and thus be ignored during subsequent import. However, I see now that strategy doesn't cover all possible use cases. It very well could be possible to have configuration in your local directory but you want to ignore certain assets. 

In any case, you have a point here and I'll need to apply a code update to make sure that exclusions apply during import too.
