### ISSUE TITLE
Does the cli tool support bot detection?

### ISSUE THREAD

**Issue by sreeramjayan** [auth0/auth0-deploy-cli#546]
### Description

Does auth0-deploy-cli support bot detection capabilities as part of attackProtection?

**Comment by willvedd** [comment]
Closing this out. Bot detection is looking like a deliverable that should arrive to the Management API in the coming quarters, but nothing firm yet as priorities shift. Until it is supported with the management API, this tool cannot implement it and are stuck waiting. Rest assured that once it becomes GA, we will work to incorporate into the tool. Until then, sit tight!
