### ISSUE TITLE
Bad Request when importing clients

### ISSUE THREAD

**Issue by giomaik** [auth0/auth0-deploy-cli#55]
Hello, I am trying to export from one tenant and import into a newly created one, both within the same private instance, and getting the following error:

`Bad Request: Payload validation error: 'Additional properties not allowed: owners'`

I'm guessing the Management API doesn't allow for custom fields? Is there any way of getting around this limitation?

Thanks

**Comment by stevezau** [comment]
@giomaik please ref to PR #56

**Comment by giomaik** [comment]
@stevezau Yes we are on the appliance. Thanks for looking into this. So I take it this field won't be exported anymore and it can safely be dropped from the YAML file?

**Comment by stevezau** [comment]
@giomaik yes, it has been set to readonly which means it won't be exported.

You can test it in the latest version.
