### ISSUE TITLE
support dotenv .env files

### ISSUE THREAD

**Issue by ilovett** [auth0/auth0-deploy-cli#561]
Would be great if `.env` files were supported?

`a0deploy --env-file .env [command]`

**Comment by willvedd** [comment]
Although maybe not the same in spirit, you're basically describing the Deploy CLI's configuration file: `a0deploy [command] -c config.json`. You certainly could consider this configuration file to be a secret, much like a .env file. 

If you still wish to augment the config file with a .env file, there are a slew of solutions available from a [DIY script](https://stackoverflow.com/questions/19331497/set-environment-variables-from-file-of-key-value-pairs) to an [off-the-shelf solution](https://www.npmjs.com/package/dotenv-cli). Supporting a third method of configuration just adds more complexity and overhead IMO. For those reasons, I don't see this as something we'd add to this tool. But the suggestion is much appreciated!
