### ISSUE TITLE
Random Timeouts

### ISSUE THREAD

**Issue by DanPatten** [auth0/auth0-deploy-cli#562]
### Description

I am using running the auth0 cli tool inside a docker container and then running a deploy in an Azure Pipeline. This seems to work sometimes, however it will randomly fail 50% of the time and just timeout at different stages. It appears some API calls time out after 60 seconds.  If I rerun the build then it works half the time. 

2022-06-02T21:11:19.256Z - info: Updated [emailTemplates]: {"syntax":"liquid","from":"","subject":"","urlLifetimeInSeconds":432000,"template":"reset_email","enabled":true}
Error: Error: Problem updating clientGrants {"id":"xxx","client_id":"xxx","audience":"[https://api.x.net/"}](https://api.x.net/%22%7D)
APIError: connect ETIMEDOUT xxx.xxx.xxx.xxx:443

### Environment

Docker container using the following
-Ubuntu 20.04
-Node 14.16.1

Started via the docker run command in a Azure Bash pipeline

```
(node:8) UnhandledPromiseRejectionWarning: APIError: connect ETIMEDOUT xxx.xxx.xxx.xxx:443
    at /Auth0/node_modules/rest-facade/src/Client.js:402:25
    at Request.callback (/Auth0/node_modules/superagent/lib/node/index.js:905:3)
    at ClientRequest.<anonymous> (/Auth0/node_modules/superagent/lib/node/index.js:822:12)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Also tried running this directly on our build agent using node and also getting similar timeouts, seems to happen randomly. Tried using the debug flag with no success.

**Comment by DanPatten** [comment]
@willvedd We figured it out, our VM in GCP had a port limit of 64, it appears that the auth0 script is not properly opening and closing (or reusing connections). Once we upped our max port limit from 64 to 1000 it worked. Can you look into making sure you are re-using the connections or properly closing them between each API request:

https://i.imgur.com/IVmwXpx.png

**Comment by bt-Knodel** [comment]
@willvedd Could you review the note above provided by the developer?  Auth0 should not be keeping over 64 connections open during the deployments correct?
