### ISSUE TITLE
Updating enable_sso flag is not allowed

### ISSUE THREAD

**Issue by stephen84s** [auth0/auth0-deploy-cli#57]
We encounter this error while trying to import an exported tenant configuration from the console. Posting it here since I haven't seen any references to the `enable_sso` flag problem anywhere in the docs.

`2018-11-27T23:39:00.465Z - error: Updating the enable_sso flag is not allowed.`

Command for exporting tenant:-
```
a0deploy export -c config.json  -f directory -o tenant/directory
```

Command for importing tenant:-
```
a0deploy import -c config.json -i tenant/directory
```

How to reproduce ?
- Create a new tenant in auth0 
- Export the tenant using the deploy CLI (any format yaml or directory will do)
- Try to reimport the same config using the auth0-deploy-cli into the same or a different tenant.
- The import will fail with the above error.

Work around:-
- Edit the generated tenant config file (tenant.json or tenant.yml)
- Delete the `enable_sso` line in `flags`. If `enable_sso` is the only flag, then delete the whole `flags` entry.
- Reimport the config, it should successfully import now.

**Comment by stevezau** [comment]
Hi @stephen84s what object are you seeing `enable_sso` on? Is it for clients?

**Comment by stevezau** [comment]
@fyockm how do you want to handle this? I believe this flag is related to the new enhance sso capabilities which is forced to 'true' for new tenants but old tenants have the option to toggle the flag.

It's a tricky case to handle, i'm thinking to add it to the readonly flags 
`https://github.com/auth0/auth0-deploy-cli/blob/master/src/readonly.js`
