### ISSUE TITLE
Add support for email providers

### ISSUE THREAD

**Issue by sgmeyer** [auth0/auth0-deploy-cli#6]
As a user I would like to deploy my email providers and templates via the deployment CLI.

**Comment by rivulent** [comment]
+1!

**Comment by heronog** [comment]
+1

**Comment by mostekcm** [comment]
Templates may have to wait for the new version of email templates.  But we could do providers sooner.

**Comment by stevezau** [comment]
This is now supported, please see the readme and examples folders.
