### ISSUE TITLE
Exeeding Management API rate limit

### ISSUE THREAD

**Issue by TAKANET7007** [auth0/auth0-deploy-cli#606]
### Description
Dump metod makes the use of api exceeds the limit of Management API endpoint.
The dump operation itself seems to worked fine, but there was a log left on Auth0 console saying "Rate Limit On API"
This was not happening at v7.11.1.

### Reproduction
Our code looks almost exactly like one in the document.
https://github.com/auth0/auth0-deploy-cli/blob/master/docs/using-as-node-module.md

Following is the log shown at auth0 console.(I excluded some records)
```
{
    "type":"api_limit",
    "description": "Global per socond default group limit has been reached",
    "details":{
        "request": {
            "method": "get",
            "path": "/api/v2/prompts/{prompt}/custom-text/{language}"
        },
       "response": {}
    }
}
```

From the log above, this seems to be related to custom prompts.
I have only one language activated but some of the prompts are customesed on my tenant.

### Environment
- **Version of this library used:** 7.14.1
- **Version of the platform or framework used, if applicable:** Node.js 16.x
- **Other relevant versions (language, server software, OS, browser):** AWS lambda
- **Other modules/plugins/libraries that might be involved:**

**Comment by willvedd** [comment]
It is normal and expected for the Deploy CLI to be operating very near or at the rate-limiting threshold. Doing so allows the tool to perform as best as it can by relying on the underlying SDK's retry logic to appropriately manage the flow of requests to the management API. This is especially true in more recent versions that support custom text prompts, as that resource type necessarily requires many dozens of requests to comprehensively build up your translations.

**Comment by TAKANET7007** [comment]
Hi

Thank you for the reply.
I agree that the retry logic will make things go right for this CLI.
But it is true that few end user will experience short service outage when rate limit occur if there is a fucntion dependent on management API.
It seems you have 'promise-pool-executor' for job management.
Is it possible not to make API go off the limit by changing API_FREQUENCY_PER_SECOND?
I tried to read through the code but I was not able to find how the requests for the "prompts" are made and managed.
