### ISSUE TITLE
Dependency on ts-node

### ISSUE THREAD

**Issue by matthieusieben** [auth0/auth0-deploy-cli#625]
### Description

Updating from `7.14.1` to `7.14.2` added `ts-node` as a dependency. It would be better if `auth0-deploy-cli` was bundled into a pure JS module rather than relying on Typescript at runtime. Or maybe was this a misplaced devDependency ?

### Reproduction

Add the latest version of `auth0-deploy-cli` as dependency. Notice that `ts-node` was installed.

### Environment

> Please provide the following:

- **Version of this library used:** `7.14.2`
- **Version of the platform or framework used, if applicable:** `v16.16.0`
- **Other relevant versions (language, server software, OS, browser):** N.A.
- **Other modules/plugins/libraries that might be involved:** `ts-node`

**Comment by willvedd** [comment]
@matthieusieben @jmac105 This has been addressed with [v7.14.3](https://github.com/auth0/auth0-deploy-cli/releases/tag/v7.14.3). Appreciate the patience and support!
