### ISSUE TITLE
Checking for unreplaced keywords fails for Universal Login Page with Lock

### ISSUE THREAD

**Issue by mlantukh-fmp** [auth0/auth0-deploy-cli#627]
### Description

Using auth0-deploy-cli, version 7.14.2, to deploy an Auth0 tenant configuration fails at the step where unreplaced keywords check is called. It happens with default Universal Login with Lock template.
Note that the previous (7.13.1) version works fine

The reason seems to be in the `login.html` template line
```JavaScript
var config = JSON.parse(decodeURIComponent(escape(window.atob('@@config@@'))));
```

Replacing `@@config@@` by "this-is-a-tmp-stub" fixed the problem but broke the login page cause the config was no longer available.

### Expected behaviour

Checking for unreplaced keywords ignores `escape(window.atob('@@config@@'))` in the template with Lock widget.

### Reproduction

* Install auth0-deploy-cli via npm i -g auth0-deploy-cli
* Using default template for Universal Login page with lock
* Run `a0deploy import -c={path to config.json} --input_file {path to input directory} `

#### Output:
```bash

Processing directory {input directory}
ERROR : Unreplaced keywords found: config. Either correct these values or add to AUTH0_KEYWORD_REPLACE_MAPPINGS configuration.
error Command failed with exit code 1.
```

### Environment

> Please provide the following:

- **Version of this library used:** 7.14.2
- **Version of the platform or framework used, if applicable:** N/A
- **Other relevant versions (language, server software, OS, browser):** N/A
- **Other modules/plugins/libraries that might be involved:** N/A

**Comment by willvedd** [comment]
There may be some confusion here around the versions. The unreplaced keyword mapping error was introduced in v7.14.0 but reverted with v7.14.1. The version you noted, v7.14.2, should not be incurring this issue. Please see the [changelog](https://github.com/auth0/auth0-deploy-cli/blob/master/CHANGELOG.md#7141---2022-06-29) for more details.
