### ISSUE TITLE
Auth0 Extensions - Auth0 Deploy CLI Version1.0  Insufficient scope

### ISSUE THREAD

**Issue by ddkserv** [auth0/auth0-deploy-cli#64]
Hi All,

The Auth0 Installed Extensions - Auth0 Deploy CLI Version1.0 has to be update to match Auth0 CLI 2.x so the Scope is setup right.
The Auth0 CLI for export require: export "read:rules_configs".

Here is the log output:
`error: Problem running command export during stage load when processing type rulesConfigs
error: {"statusCode":403,"error":"Forbidden","message":"Insufficient scope, expected any of: read:rules_configs","errorCode":"insufficient_scope"}`

**Comment by ddkserv** [comment]
Grant type: Client credintial is also missing!

**Comment by stevezau** [comment]
Have you tried the latest version 2.0.1? it's required for deploy-cli v2.

https://github.com/auth0-extensions/auth0-deploy-cli-extension/blob/master/package.json#L3

**Comment by fyockm** [comment]
We will not be updating Deploy CLI v1.0. Please upgrade to v2.x.
