### ISSUE TITLE
Importing tenant configs using CLI fails

### ISSUE THREAD

**Issue by aimranov27** [auth0/auth0-deploy-cli#645]
### Description
I exported a `tenant.yaml` file from one tenant and am trying to import into the other tenant. 
When trying to do this I'm getting this error:
```
error: Problem running command import
error: Problem deploying rules
```

Even when I remove rules other errors start appearing and basically the import never goes through.

### Environment

> Please provide the following:

- **Version of this library used: auth0 version 7.14.1**

**Comment by matthewmuscat** [comment]
@aimranov27 what fixed this? I am currently getting the same error but for `error: Problem deploying actions`. It works locally but just not in CI.
