### ISSUE TITLE
blank branding.logo_url is exported if I don't set anything to Company Logo, but this configuration causes failure while importing

### ISSUE THREAD

**Issue by shibayu36** [auth0/auth0-deploy-cli#656]
### Description
I don't set anything to Company Logo in "Branding > Universal Login", and I execute `a0deploy export`, then it exports blank branding.logo_url like following

branding/branding.json
```json
{
  "colors": {
    "page_background": "#000000",
    "primary": "#ea5323"
  },
  "logo_url": ""
}
```

After exporting, I execute `a0deploy import` using these exported settings, then this command failed with error.

```
2022-09-20T14:07:14.738Z - error: Problem running command import during stage processChanges when processing type branding
2022-09-20T14:07:14.738Z - error: Payload validation error: 'Object didn't pass validation for format strict-https-uri-or-null: ' on property logo_url (URL for the logo. Must use HTTPS).
```

### Reproduction

- Set blank to Company Logo in "Branding > Universal Login"
    - <img width="502" alt="image" src="https://user-images.githubusercontent.com/1132489/191283388-5a070d0f-cc88-4e59-958a-c661501d44e4.png">
- Execute `a0deploy export`
- Execute `a0deploy import`

### Environment

> Please provide the following:

- **Version of this library used:** 7.14.3
- **Version of the platform or framework used, if applicable:** Private Cloud v202235.81.6
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

**Comment by willvedd** [comment]
This has been addressed with [7.15.1](https://github.com/auth0/auth0-deploy-cli/releases/tag/v7.15.1).

**Comment by shibayu36** [comment]
> Can you think of any reasons why your tenant would be returning that value? Is it a brand new tenant? Private cloud? Are you using classic login?

I use Private Cloud and classic login.  I don't need to set `logo_url` because I use a full customized HTML for classic login.

> I've tried again, and I still can't recreate this issue, for either YAML or directory formats

hmm...
Before, I found that some fields were not exported but once I pressed a save button in the Dashboard then those fields appeared with blank.  So you may reproduce it if you press the save button in "Branding > Universal Login" with changing a primary color and keeping logo_url blank.

**Comment by shibayu36** [comment]
I think it is a problem on the API side.  So I also created a ticket to support.auth0.com
