### ISSUE TITLE
Externalize secrets and sensitive values

### ISSUE THREAD

**Issue by matt-filion** [auth0/auth0-deploy-cli#66]
This is less of an issue and more of an awareness deal. I created an NPM module that will take care of this via secret manager, as well as adding some double hash lockups within the configuration file itself.

https://github.com/matt-filion/auth0-deploy-cli-config-values/blob/master/README.md

**Comment by neurotrack-matt** [comment]
Just realised this has a few flaws. I'm going to rework it it a bit. Want it to operate on the yaml directly, its silly to use the .json file, was a lazier implementation.

**Comment by matt-filion** [comment]
Withdrawing this suggestion, it needs re-working. It should never have acted on the JSON file.
