### ISSUE TITLE
Only export tenant setting yaml file when using Auth0-deploy-cli

### ISSUE THREAD

**Issue by andyvotvf** [auth0/auth0-deploy-cli#680]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-deploy-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://github.com/auth0/auth0-deploy-cli#documentation) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-deploy-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-deploy-cli/releases/latest) of this tool and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I want to export only tenant yaml settings file but when I using  Auth0-deploy-cli as Node modules, not only generate yaml files we also have databases, hooks, pages,rules folder. 

I think if I just generate yaml file, the time to run will be shorter.

### Expectation

Only export yaml settings file

### Reproduction

1. Run  Auth0-deploy-cli as Node module
2.  Run Auth0-deploy-cli as CLI

### Deploy CLI version

^7.15.1

### Node version

v16.13.0

**Comment by willvedd** [comment]
The files and directories you mention are necessary artifacts for managing the resources within your tenant. It seems to me that you would like to exclude certain resources from being managed, for that please refer to the docs on [excluding resources from management](https://github.com/auth0/auth0-deploy-cli/blob/master/docs/excluding-from-management.md).
