### ISSUE TITLE
Sandbox_version is imported but cannot be exported

### ISSUE THREAD

**Issue by hmd34** [auth0/auth0-deploy-cli#682]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Hello, I manage my Auth0 configuration with a0deploy. Thanks for creating and maintaining this cli.
On the main topic, I found that the Node.js version of the tenant settings is not exported by a0deploy. But, I seem there is looks like setting(`sandbox_version`) in this repo. 

I want to manage Node.js version with a0deploy, and I found related PR and issue. 
- PR: https://github.com/auth0/auth0-deploy-cli/pull/99
- Issue: https://github.com/auth0/auth0-deploy-cli/issues/69

That issue says 3 years ago, you could exported sandbox_version setting, but couldn’t imported.
So I tried to following steps, and checked that can import `sandbox_version` now.
1. Checked tenant runtime version. It was Node 12
2. Added `sandbox_vevrsion: “16”` in tenant.json
    - Like this sample: https://github.com/auth0/auth0-deploy-cli/blob/c261f5688713299e8e85e2bd17c399d26c31f6ba/examples/directory/tenant.json#L6
4. Imported setting with a0deploy
5. Checked tenant runtime version. It was Node 16

### Describe the ideal solution

Erase `sandbox_version` from readonly.ts.
https://github.com/auth0/auth0-deploy-cli/blob/9f30c1acf13f410a0a893ed621e1506d1989fc92/src/readonly.ts#L11

**Comment by willvedd** [comment]
@hmd34 thanks for the contribution! This was auto-closed when your PR was merged but it is not available through release yet. I expect that to happen within the next couple of days though.

**Comment by willvedd** [comment]
This has been released with [7.16.0](https://github.com/auth0/auth0-deploy-cli/releases/tag/v7.16.0). Thanks for opening the issue and apologies on the delay!
