### ISSUE TITLE
Sandbox_version is exported but cannot be imported

### ISSUE THREAD

**Issue by giomaik** [auth0/auth0-deploy-cli#69]
Hello, we have some auth0 tenants using the appliance deployment model. When we use the tool to export we get a line like `sandbox_version: '4'` but when we try to import the same yaml file we get an error like `The sandbox_version provided is invalid. Please use one of the available options: []`. Is there a way around this without having to manually edit the yaml file, please?

Thanks

**Comment by stevezau** [comment]
Hi @giomaik, I believe you can just remove the sandbox_version and it should work.

It depends what appliance version you are on, i believe they force version 8 now. However the api should return that, i've let the appliance team know.

Can you try with version 8 or removing it?
