### ISSUE TITLE
"Error calling branding API, Template does not exist., status code: 404"

### ISSUE THREAD

**Issue by jcerjak** [auth0/auth0-deploy-cli#691]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-deploy-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://github.com/auth0/auth0-deploy-cli#documentation) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-deploy-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-deploy-cli/releases/latest) of this tool and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When running `export` with `--debug` flag, I see the following error in the logs:

```
$ a0deploy export -c config.json -f yaml -o config/ --debug
...
2022-11-11T14:51:08.715Z - info: Retrieving roles data from Auth0
2022-11-11T14:51:09.069Z - debug: Error calling branding API, Template does not exist., status code: 404
2022-11-11T14:51:09.070Z - info: Retrieving branding data from Auth0
...
```

### Expectation

No error is shown in the log.

### Reproduction

Not sure how to reproduce the issue. I have a custom email template for the Passwordless connection, and I've customized Verification Email template (but reverted those changes). See also #690, maybe it's somehow related.

### Deploy CLI version

7.15.1

### Node version

v18.12.1

**Comment by willvedd** [comment]
Is the issue here the presence of that error in the output? If so, I believe that's perfectly fine. Note the debug log level, it's an error in the context of Auth0's Management API, but not within the Deploy CLI. Looking closer at the code, I believe this error occurs if no universal login template exists, which is a valid tenant state. Can you confirm that there are no other functional issues here?

Also, I may recommend dropping the `--debug` flag for most invocations, unless you're actively troubleshooting an issue.

**Comment by jcerjak** [comment]
> Looking closer at the code, I believe this error occurs if no universal login template exists, which is a valid tenant state. Can you confirm that there are no other functional issues here?

We have a custom template for Login. Maybe at some point we enabled custom template for Password Reset and MFA, then disabled it, and this is causing the 404 to occur. In any case, there are no other functional issues, so closing the ticket.
