### ISSUE TITLE
a0deploy branding endpoint really slow on export

### ISSUE THREAD

**Issue by danielesie1988** [auth0/auth0-deploy-cli#692]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-deploy-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://github.com/auth0/auth0-deploy-cli#documentation) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-deploy-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-deploy-cli/releases/latest) of this tool and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi,

I'm facing an issue during the a0deploy export usage, it look likes the branding export is really slow:

`a0deploy export --config_file=config.json --format=yaml...
...
2022-11-14T09:04:23.370Z - info: Retrieving roles data from Auth0
2022-11-14T09:04:25.739Z - info: Retrieving branding data from Auth0
2022-11-14T09:19:54.092Z - info: Retrieving prompts data from Auth0
2022-11-14T09:19:54.271Z - info: Retrieving migrations data from Auth0
...`

As you can see the branding steps usually takes from 10 to 15 minutes.

From time to time  I'm also getting a failure in the same step:
`2022-11-14T07:06:08.162Z - info: Retrieving roles data from Auth0
2022-11-14T07:06:08.525Z - info: Retrieving branding data from Auth0
2022-11-14T07:06:22.802Z - error: Problem running command export
2022-11-14T07:06:22.802Z - error: Problem loading tenant data from Auth0 APIError: write EPROTO C0B7CF24B7710000:error:0A000410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1600:SSL alert number 40`

Is there a know issue/limitatiion on the brandding export?

Regards
Daniele

### Expectation

The branding export ends in reasonable time

### Reproduction

a0deploy export --config_file=config.json --format=yaml...

### Deploy CLI version

7.15.1

### Node version

14

**Comment by willvedd** [comment]
It appears that the slow step is the prompts retrieval. This would make sense because that is a particularly expensive operation if you're operating multiple languages in a free-tiered tenant. I recommend either excluding prompts from the purview of management through the `AUTH0_EXCLUDED` [configuration property](https://github.com/auth0/auth0-deploy-cli/blob/master/docs/excluding-from-management.md#excluding-entire-resources-by-type) if you wish to skip this step.
