### ISSUE TITLE
Allow for a list of included modules (currently only excluded)

### ISSUE THREAD

**Issue by freakyfelt** [auth0/auth0-deploy-cli#702]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Currently the CLI tool only allows for an `AUTH0_EXCLUDED` list of modules, which means that splitting the config across multiple packages (e.g. when the `pages` are compiled and uploaded separately) requires enumerating the entire list of other modules to exclude. Instead it would be nice to have the ability to only include the pages module in this instance.

### Describe the ideal solution

a new config option for `AUTH0_INCLUDED` is available that allows users of the CLI to specify a list of modules that will be processed for export/import.

### Alternatives and current workarounds

Current workaround is to enumerate the entire list of modules and exclude the ones that are not relevant to the package.

**Comment by freakyfelt** [comment]
Ah looks like this is already a mentioned proposal in https://github.com/auth0/auth0-deploy-cli/issues/451

**Comment by willvedd** [comment]
I can envision the general use case but do you mind explaining your personal use case? Doing so can help us better understand how folks use this tool.

But aside from that, I agree that this configuration option would be very helpful. Auth0 is constantly expanding its product offerings so its expected to be constantly updating an exclude list. The key is to clearly distinguish from `AUTH0_EXCLUDED`, I think the API language needs to be tweaked a bit, perhaps `AUTH0_ONLY_INCLUDE` or similar. And validation would need to be put in place to prevent their simultaneous usage.

This is something I expect us to deliver eventually, but cannot commit to specific timeframe.

**Comment by freakyfelt** [comment]
We are looking to use a separate directory/monorepo package to build and deploy the login and error pages for auth0 aside from our standard auth0 configuration files with an eye toward splitting more configuration to other packages. Unfortunately that requires us to manually exclude the correct modules in each package instead of specifying which modules should be included.

```text
|- packages/
  |- config/
    |- actions/
    |- ...
  |- pages/
    |- package.json
    |- dist/
    |- public/
    |- src/
    |- test/
```

**Comment by barzl** [comment]
I would love to have the ```AUTH0_INCLUDED``` option.
We have a mix of clients, some are constant and deployed through the CLI tool, and some are dynamic and managed with management API.
So we need a way to explicitly state which clients should be updated via the CLI tool and ignore the rest.
This is better than fetch a list of all existing clients each CLI tool import operation and set the ones to ignore in CLI tool's config.

**Comment by willvedd** [comment]
Good news! We've added this functionality in the [7.16.0](https://github.com/auth0/auth0-deploy-cli/releases/tag/v7.16.0) release via the `AUTH0_INCLUDED_ONLY` configuration property. Its usage is documented on the [excluding from management](https://github.com/auth0/auth0-deploy-cli/blob/master/docs/excluding-from-management.md#inclusion-example) and [configuring the Deploy CLI](https://github.com/auth0/auth0-deploy-cli/blob/master/docs/configuring-the-deploy-cli.md#auth0_included_only) pages. 

Personally, this is something I've always wanted to add because it makes the tool easier to test. So thanks for the suggestion, it was the nudge we needed!
