### ISSUE TITLE
Support comparing source control config to tenant config

### ISSUE THREAD

**Issue by stevezau** [auth0/auth0-deploy-cli#71]
Should we support the ability to compare/diff your local config to what is in the auth0 tenant.

"Tell me what has changed in my production env compared to my local env"

**Comment by esalter** [comment]
This would be fantastic to see, especially if it took env vars/replacements into account.  The use case would be to validate that we aren't experiencing drift because of people updating config outside source control, and add ability to alarm if differences are found.

**Comment by Legion2** [comment]
This would also help validating, initially exported configuration before starting the import. How is it currently possible to verify that importing an initial export will not cause major problems or data loss.

**Comment by willvedd** [comment]
Thanks for opening this ticket. I agree that this is not only useful but crucial for some folks' development workflows. We don't have a roadmap for this tool completely set, but this is definitely on our radar. Regardless, it is a duplicate to #70, which has a healthy discussion so I'm closing this ticket in favor of that one.
