### ISSUE TITLE
Datadog logStreams don't import when exported from a known working tenant

### ISSUE THREAD

**Issue by qbunt** [auth0/auth0-deploy-cli#716]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-deploy-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://github.com/auth0/auth0-deploy-cli#documentation) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-deploy-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-deploy-cli/releases/latest) of this tool and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Exporting with a newly configured `logStreams` objects from a paid tenant does not import properly on a paid tenant, with a known working key. For instance:

When exported from the tenant, `tenant.yaml` is updated to (with the straight API key unfortunately):
```yaml
logStreams:
  - name: Datadog
    sink:
      datadogRegion: us
      datadogApiKey: ##DATADOG_API_KEY##
    status: active
    type: datadog
```
and on import _of the same yaml file_, I get this response back from the CLI

```bash
2023-01-11T22:44:49.433Z - error: Problem running command import during stage processChanges when processing type logStreams
2023-01-11T22:44:49.433Z - error: Problem updating logStreams "Datadog"
Bad Request: Payload validation error: 'Data does not match any schemas from 'oneOf'' on property sink.
2023-01-11T22:44:49.433Z - info: Please refer to the Auth0 Management API docs for expected payloads: https://auth0.com/docs/api/management/v2
```

### Expectation

Properly imported logStreams for the Datadog log stream.

### Reproduction

1. Export configuration from a known working tenant with a `logStream` configured to Datadog
2. Observe `config/tenant.yaml` and see the new `logStreams` block
```yaml
logStreams:
  - name: Datadog
    sink:
      datadogRegion: us
      datadogApiKey: ##DATADOG_API_KEY##
    status: active
    type: datadog
```
3. Import the same configuration via `a0deploy import --input_file config/tenant.yaml --config_file ./test.json` into a _paid_ tenant
4. Observe the following
```bash
2023-01-11T22:44:49.433Z - error: Problem running command import during stage processChanges when processing type logStreams
2023-01-11T22:44:49.433Z - error: Problem updating logStreams "Datadog"
Bad Request: Payload validation error: 'Data does not match any schemas from 'oneOf'' on property sink.
2023-01-11T22:44:49.433Z - info: Please refer to the Auth0 Management API docs for expected payloads: https://auth0.com/docs/api/management/v2
```    

### Deploy CLI version

7.15.1

### Node version

16.11.0

**Comment by willvedd** [comment]
Based on the API validation error, I'm fairly certain that the issue is with the `##DATADOG_API_KEY##` replacement. I would make sure that value exists in your `./test.json` configuration file.

**Comment by qbunt** [comment]
@willvedd I can assure you that the value is in that file under the replacements block

**Comment by qbunt** [comment]
@willvedd the value for the API key was in the wrong block section (this tenant has a ton of configuration in it), so the placement in the config file was the issue. Value was present, but not in the replacement block as I thought it was. My apologies for the confusion.

> Further, the 'Data does not match any schemas from 'oneOf'' on property sink error, while not immediately obvious, means the sink property is expecting to match one of several predefined patterns. This is to facilitate validation against the different types of log streams. If the API key is not defined, it is unable to match the object pattern, resulting in that error.

That error message read to me as an implementation error rather than something that I, the foolish end user did incorrectly. Given the limited set of values for this logStream, messaging could simply be improved.

Auth0 broadly seems to advise using the Terraform provider for tenant config in CI and elsewhere. Should I plan on migrating that tool instead of this one?

**Comment by qbunt** [comment]
Super helpful, thanks @willvedd, have a great weekend
