### ISSUE TITLE
Export without secrets

### ISSUE THREAD

**Issue by giomaik** [auth0/auth0-deploy-cli#72]
Hello, 

Is it possible to export a yaml file stripping out the client secrets? It doesn't look like it. If not, it would be a great idea as we are looking to use an export of the current state before a deploy as an artifact for rollback and we wouldn't want it to contain sensitive info.

Thanks

**Comment by stevezau** [comment]
I do like this idea. It's almost changing the option --strip to

`--strip-ids` and `--strip-sensitive`

@fyockm thoughts?

**Comment by fyockm** [comment]
Yes, seems reasonable to me.

`--strip-ids` and `--strip-sensitive` make sense.  Just need to decide what all properties would be considered "sensitive".

**Comment by omar** [comment]
Would it be fair to say that if you're trying to use this tool to create an authoritative configuration as code for your Auth0 setup that can be applied and promoted to different tenants (Dev, QA, Prod, etc.), you shouldn't export Auth0 settings with IDs or secrets?

If that's the case (and it is for our use case), then I'd encourage we change the CLI to behave that way by default and make export IDs and secrets an opt-in feature.

**Comment by stevezau** [comment]
@omar i agree, will flag with team
