### ISSUE TITLE
enabled_clients not working in database.json

### ISSUE THREAD

**Issue by zikes** [auth0/auth0-deploy-cli#78]
After running an export of my tenant's configuration with the a0deploy tool and subsequently re-importing the results, I've found that the `enabled_clients` field of the `/database-connections/dbname/database.json` file is apparently ignored. The export filled this array with client names, and I have tried replacing them with their associated IDs, however in both instances after a deploy occurs the applications have all been disabled in the connection.

**Comment by zikes** [comment]
This issue is regarding the Gitlab Deployment extension, closing here to re-evaluate and re-open in a more appropriate location.

**Comment by fyockm** [comment]
@zikes all deployment extensions were updated today. Please see our new deployment extensions monorepo: https://github.com/auth0-extensions/auth0-deploy-extensions
