### ISSUE TITLE
Export from a new tenant includes non-permitted flag require_signed_request_object

### ISSUE THREAD

**Issue by yossarian21** [auth0/auth0-deploy-cli#788]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-deploy-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://github.com/auth0/auth0-deploy-cli#documentation) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-deploy-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-deploy-cli/releases/latest) of this tool and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I set up a new tenant and exported config from it using `format: 'yaml'`.

The resulting `tenant.yaml` includes:

```yaml
tenant:
  flags:
    require_signed_request_object: false
```

If I immediately try to import this into the same tenant, I get an error:

```shell
Bad Request: Updating the require_signed_request_object flag is not allowed. Please contact us if you need additional information.
    at fn (/app/node_modules/rest-facade/src/Client.js:402:25)
    at Request.callback (/app/node_modules/superagent/src/node/index.js:923:3)
    at fn (/app/node_modules/superagent/src/node/index.js:1153:18)
    at IncomingMessage.<anonymous> (/app/node_modules/superagent/src/node/parsers/json.js:19:7)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  statusCode: 400,
  requestInfo: {
    method: 'patch',
    url: 'https://<tenant>.us.auth0.com/api/v2/tenants/settings'
  },
```

I can't find this flag in the tenant settings UI (or I don't understand what it is) but I haven't modified any of the tenant-level settings other than inviting members, setting a Friendly Name, and setting the Logo URL.

Workaround: Remove `require_signed_request_object` from `flags`

### Expectation

I should be able to re-import the config that was just exported from a new tenant.

### Reproduction

1. Given I have just created a new tenant and set up a Deploy CLI M2M application
2. When I export the tenant config to YAML
3. Then I should be able to re-import the same config to the same tenant
4. Bug: I get a bad request error

### Deploy CLI version

7.17.2

### Node version

18.16.0

**Comment by andreas-lundgren-qlucore** [comment]
Maybe something to consider: The fact that an export also obfuscate access keys also makes an export impossible to directly import, since it will replace the actual credentials with these markers created by the export. If this bug is addressed, I would suggest the export to omit the `credentials` property all together, or the import to ignore/warn for this specific value (that is to be considered to be a marker rather than an actual value).

emailProvider:
  credentials:
    accessKeyId: '##SES_ACCESS_KEY_ID##'
    secretAccessKey: '##SES_ACCESS_SECRET_KEY##'

**Comment by willvedd** [comment]
@yossarian21 As you've discovered, some exported tenant flags are not compatible with new tenants. This situation can arise for a myriad of reasons, but most notably can occur if the target tenant was created at a time where certain feature flags were deprecated. 

In these cases, it is safe to remove the `require_signed_request_object` (or any other problematic flag) property entirely. I do admit that this situation is annoying, so we are investigating the possibility of checking flag compatibility before writing to the tenant. This work has even been proposed with #792 but has not been thoroughly vetted yet.

**Comment by willvedd** [comment]
@andreas-lundgren-qlucore what you are describing is a separate from OP's issue. Please open a separate issue for tracking.
