### ISSUE TITLE
Exporting a tenant multiple time should result in the same tenant.yml

### ISSUE THREAD

**Issue by hjdarnel** [auth0/auth0-deploy-cli#82]
Currently, running `a0deploy export -f yaml` multiple times does not result in the same `tenant.yml`. In specific, the multiple `emailTemplates` in `tenant.yml` are not in the same order after each export. 

This makes it really difficult to compare changes programmatically after exporting settings. Maybe these need to be sorted by value (i.e. `emailTemplates.template`'s value) so that there aren't blocks of config moving around unnecessarily.

I would assume this could apply to other multi-value properties too.

**Comment by stevezau** [comment]
@hjdarnel I agree. It's on the TODO list to sort by naming fields and to also try add comments / spaces between sections. @twistedstream FYI.
