### ISSUE TITLE
Getting an unknown APIError: {} while trying to export our tenant configuration.

### ISSUE THREAD

**Issue by vasantteja** [auth0/auth0-deploy-cli#829]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-deploy-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://github.com/auth0/auth0-deploy-cli#documentation) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-deploy-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-deploy-cli/releases/latest) of this tool and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

We have a dev and prod environment for auth0. For dev we could comfortably import and export the tenant configuration. But for prod we are getting an unknown APIError: {} while trying to export the tenant configuration. I turned on the debug flag and I got this error log
`
2023-07-27T13:51:53.898Z - debug: APIError: {}
    at /opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/auth0-deploy-cli/node_modules/rest-facade/src/Client.js:402:25
    at Request.callback (/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/auth0-deploy-cli/node_modules/superagent/lib/node/index.js:943:3)
    at IncomingMessage.<anonymous> (/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/auth0-deploy-cli/node_modules/superagent/lib/node/index.js:1165:20)
    at Stream.emit (node:events:513:28)
    at Stream.emit (node:domain:489:12)
    at Unzip.<anonymous> (/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/auth0-deploy-cli/node_modules/superagent/lib/node/unzip.js:53:12)
    at Unzip.emit (node:events:513:28)
    at Unzip.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: Process completed with exit code 1.
`

### Expectation

I want to import and export tenant configuration in prod. The error message doesn't provide any extra context around why this is happening. Can you please help me by telling me what's happening here or how I can debug this kind of error.

### Reproduction

1.Given: We are using deploy cli with version 7.18.0 in our github actions workflow.
2.When: We are running `a0deploy export -c=config.json --format=yaml --output_folder=local --debug=true` command its failing with an error.
3.Then: We are getting this error. We tried with the dev credentials and everything is running fine. But with prod credentials it's failing. We have the same permissions for both dev and prod client.

### Deploy CLI version

7.18.0

### Node version

16.20.1

**Comment by willvedd** [comment]
Are you able to retry and report if this issue is still continuing? I'm not able to recreate nor do we have any other tickets pertaining to this. The nondescript nature of the error suggests to me that it may have been a one-off.

**Comment by vasantteja** [comment]
Hi @willvedd. Thanks a lot for taking a look into this. This was an error because we didn't whitelist our github actions ip address. The job is working fine after whitelisting those ips. I will close this ticket as our job is working now.

**Comment by willvedd** [comment]
@vasantteja Thanks for following-up and providing the explanation! Glad you figured it out.

**Comment by itahavcu** [comment]
Hi @vasantteja, I'm running into the same `APIError: {}` trying to test importing a tenant configuration from my local machine. Can you share where in the Auth0 tenant dashboard you were able to edit the list of whitelisted IPs?
