### ISSUE TITLE
Excluding clients in production

### ISSUE THREAD

**Issue by drjaydenm** [auth0/auth0-deploy-cli#83]
Hi there,
Great work on this CLI tool, it makes managing configurations across tenants really easy.

We are using the directory format with JSON files and have created the JSON config required for our API Test Clients. This is all working correctly. However these API Test Clients get deployed out to production like everything else in the repo.

I can see there are options for excluding certain rules and resource servers, however nothing exists for clients. We were wondering how you would advise managing API Test Clients across environments using the CLI tool.

Is it as simple as adding an exclude option to this CLI tool for excluding clients too? Or is there something simple we are missing here?

Thanks in advance for your help

**Comment by johankvint** [comment]
We would really like this feature too.
In our test tenants we have additional clients setup to be used for generating tokens in different ways that we do not want in production.

**Comment by fyockm** [comment]
published as `auth0-deploy-cli@3.1.0`
