### ISSUE TITLE
docs(issues): link is broken

### ISSUE THREAD

**Issue by andreasgrimm** [auth0/auth0-deploy-cli#832]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-deploy-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://github.com/auth0/auth0-deploy-cli#documentation) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-deploy-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-deploy-cli/releases/latest) of this tool and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

[Here](https://github.com/auth0/auth0-deploy-cli/issues/new/choose) the "Open" link for "🤔 Help & Questions" seems broken.

### Expectation

After navigating the correct page should be displayed.

### Reproduction

Go [here](https://github.com/auth0/auth0-deploy-cli/issues/new/choose) and navigate yourself.

### Deploy CLI version

not relevant

### Node version

not relevant

**Comment by willvedd** [comment]
Thanks for reporting! Fixed in #834 .
