### ISSUE TITLE
"error: self-signed certificate in certificate chain" during export command

### ISSUE THREAD

**Issue by aashaikh89** [auth0/auth0-deploy-cli#835]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-deploy-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://github.com/auth0/auth0-deploy-cli#documentation) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-deploy-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-deploy-cli/releases/latest) of this tool and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/tag/auth0-deploy-cli) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Self signed error received on export command. No self signed cert exists in cert manager.

C:\Users>a0deploy export -c=config.json --format=yaml --output_folder=local-demo
2023-08-04T06:30:10.939Z - error: Problem running command export
2023-08-04T06:30:10.940Z - error: self-signed certificate in certificate chain

### Expectation

Should export the tenant files and yaml

### Reproduction

a0deploy export -c=config.json --format=yaml --output_folder=local-demo

### Deploy CLI version

7.18.0

### Node version

v18.16.0

**Comment by willvedd** [comment]
@aashaikh89 I believe this error is occurring within your immediate network. We have seen this error when users are running proxies or DLP software (ex: Zscaler). I can say with some certainty that this is unlikely to originate from the Auth0 Management API. To test, can you run the Deploy CLI outside your current environment?
