### ISSUE TITLE
Add Support for branding theme

### ISSUE THREAD

**Issue by g8rswimmer** [auth0/auth0-deploy-cli#841]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

The auth0 management APi v2 has support for [branding themes](https://auth0.com/docs/api/management/v2/branding/post-branding-theme), however I am unable to find support for this API within the tool.

I would like to understand if this feature can be added to the tool.

### Describe the ideal solution

I would like for
* Support to brand themes
* Examples around directory and file structure

**Comment by willvedd** [comment]
Branding themes are already supported as "themes". Please open a new issue if the current handling of branding themes is insufficient in some way!
