### ISSUE TITLE
Support import/export from Authorization Extension

### ISSUE THREAD

**Issue by ncknuna** [auth0/auth0-deploy-cli#85]
I'm interested in using the Auth0 Authorization Extension (https://auth0.com/docs/extensions/authorization-extension/v2), and would like to have it integrated with this deploy CLI so I can manage it entirely in config. Is this something you folks would consider? :)

**Comment by fyockm** [comment]
@ncknuna sorry, we will not consider adding support for the authorization extension in the deploy cli.

> We are in the process of developing Authorization as part of our core platform and will be focusing our efforts on advancing the core platform vs the extension.

https://github.com/auth0/auth0-authorization-extension/issues/245#issuecomment-457042747
