### ISSUE TITLE
GH docs not aligned with auth0.com/docs

### ISSUE THREAD

**Issue by caileyfitzgerald** [auth0/auth0-deploy-cli#851]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-deploy-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://github.com/auth0/auth0-deploy-cli#documentation) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-deploy-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-deploy-cli/releases/latest) of this tool and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/tag/auth0-deploy-cli) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Documentation for "excluding resources from management" differs between the [GitHub docs](https://github.com/auth0/auth0-deploy-cli/blob/master/docs/excluding-from-management.md#excluding-entire-resources-by-type) and [Auth0 docs](https://auth0.com/docs/deploy-monitor/deploy-cli-tool/excluding-resources-from-management), specifically in reference to supported resource types.

#### GH docs

> All supported resource values for exclusion:
> ```actions, attackProtection, branding, clientGrants, clients, connections, customDomains, databases, emailProvider, emailTemplates, guardianFactorProviders, guardianFactorTemplates, guardianFactors, guardianPhoneFactorMessageTypes, guardianPhoneFactorSelectedProvider, guardianPolicies, logStreams, migrations, organizations, pages, prompts, resourceServers, roles, tenant, triggers```

#### Auth0 docs

> All supported resource values for exclusion: 
> ```actions, attackProtection, branding, clientGrants, clients, connections, customDomains, databases, emailProvider, emailTemplates, guardianFactorProviders, guardianFactorTemplates, guardianFactors, guardianPhoneFactorMessageTypes, guardianPhoneFactorSelectedProvider, guardianPolicies, hooks, logStreams, migrations, organizations, pages, prompts, resourceServers, roles, rules, rulesConfigs, tenant, triggers```

It is not entirely clear which (if any) is the most up-to-date or should be used as the source of truth. Without further investigation, I am not certain whether all of the other pieces of documentation are aligned as well.

### Expectation

I would expect consistency across the two sources of documentation, with both showing the same options for resource management exclusion and inclusion.

### Reproduction

1. View [GitHub documentation](https://github.com/auth0/auth0-deploy-cli/blob/master/docs/excluding-from-management.md#excluding-entire-resources-by-type) for `auth0-deploy-cli`
2. View [Auth0 documentation](https://auth0.com/docs/deploy-monitor/deploy-cli-tool/excluding-resources-from-management) for `auth0-deploy-cli`

### Deploy CLI version

latest

### Node version

latest

**Comment by willvedd** [comment]
@caileyfitzgerald Thanks for reporting this; it is a very astute observation! But yes, I can see this being frustrating. In this specific case, we've removed `hooks` and `rules` from the list of supported resources in an attempt to discourage their usage due to upcoming deprecations ([related](https://auth0.com/blog/preparing-for-rules-and-hooks-end-of-life/)). I've brought this up internally and hoping to have the Auth0 docs site updated to reflect.

We do our best to keep the two sets of documentation in sync, but as you've observed, there are occasional drifts. In those cases, it is recommended to use this repo's documentation as the source of truth. 

Hope this helps!
