### ISSUE TITLE
Support Terraform

### ISSUE THREAD

**Issue by omar** [auth0/auth0-deploy-cli#86]
I appreciate the effort put into this project, but it's lacking some key functionality that makes it difficult to comfortably use in a production environment. Specifically:

- Hiding sensitive values (e.g. `client_secret` and connection specific settings).
- Pulling sensitive values from a different source (like AWS Secret Manager, k8s Secrets, or Azure KeyVault).
- Dry run before pushing a change to see impact on editing/deleting/creating resources.
- Environment switching. For example only deploying certain clients for production or changing the values depending on environment.

These challenges have been tackled well with Terraform and there's a community driven provider being developed here https://github.com/yieldr/terraform-provider-auth0.

It would be great if Auth0 took that project as the official Terraform provider so we can leverage a lot of the lifecycle management that Terraform provides out of the box instead of duplicating that effort in this project.

**Comment by willvedd** [comment]
Good news folks! Auth0 has acquired @alexkappa's Terraform provider and will be officially support by the team. Please see the [official announcement](https://github.com/auth0/terraform-provider-auth0/issues/75) and the [repo](https://github.com/auth0/terraform-provider-auth0) for more information. 

More language needs to be developed around the positioning of each tool, but in general, the Terraform provider is a good option for folks who already adopt it into their development workflows. Whereas the Deploy CLI remains a solid choice for folks who haven't adopted TF yet or who frequently need to manage tenant configurations in bulk.

Lots of credit to @sergiughf for all his hard work on getting this project ready for more widespread consumption!
