### ISSUE TITLE
Support prompt partial import/export

### ISSUE THREAD

**Issue by kirkokada** [auth0/auth0-deploy-cli#916]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I would greatly appreciate if the deploy cli supported the import/export of prompt partials as detailed in the management api: 

https://auth0.com/docs/api/management/v2/prompts/put-partials
https://auth0.com/docs/api/management/v2/prompts/get-partials

### Describe the ideal solution

the ideal for e.g. directory format would be something like:

```
# dir structure
prompts/
  partials/
    sign-in/
      form-content-end.html
    partials.json

# prompts.json
{
  "sign-in": {
    "form-content-end": promts/partials/sign-in/form-content-end.html
  }
}
```

### Alternatives and current workarounds

The current workaround is to use the management api directly.

**Comment by mhautala** [comment]
The latest version of auth0 deploy client (^7.24.2) exported partials. But does not seem to support importing using the same folder structure.

**Comment by rickode1** [comment]
I have tried using the structure described here https://github.com/auth0/auth0-deploy-cli/pull/886 which used to work for a while and now it apparently does not anymore. "error: Payload validation error: 'Additional properties not allowed: partials'."
Is there currently a correct way of importing partials trough deploy cli?

**Comment by kirkokada** [comment]
The structure of `partials/prompts.json` should look something like:
```
{
  "login-id" : [
    {
      "login-id": [
        {
          "name": "form-content-end",
          "template": "path/to/template.liquid"
        }
      ]
    }
  ]
}
```

I'm not sure why the partials for a prompt are nested two layers deep but this is the structure that `a0deploy dump` spits out.

**Comment by kirkokada** [comment]
This feature is now supported
