### ISSUE TITLE
Upgrade version of Auth0 SDK to '^4.x.x' in Auth0 Deploy cli dependencies

### ISSUE THREAD

**Issue by DanielSzopa** [auth0/auth0-deploy-cli#922]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I would be very grateful if you would upgrade [Auth0 sdk](https://www.npmjs.com/package/auth0) to version "^4.x.x" in auth0 deploy cli dependencies.
I would like to import tenant.yaml via auth0 deploy cli, in order to update customDomains section, but possibility was added to Auth0 SDK in version 4.x.x when auth0 deploy cli supports only 3.x.x.

Current state
https://github.com/auth0/auth0-deploy-cli/blob/v7.22.1/package.json

```json
"dependencies": {
    "auth0": "^3.0.0",
  },
```

### Describe the ideal solution

Ideal solution will be upgrade auth0 sdk version in [package.json](https://github.com/auth0/auth0-deploy-cli/blob/master/package.json).

```json
"dependencies": {
    "auth0": "^4.0.0",
  },
```

**Comment by eturino** [comment]
There is also the issue of nested dependencies. auth0 v3 uses an old version of axios which has a security issue, afaik

**Comment by DanielSzopa** [comment]
Thanks for your support!
