### ISSUE TITLE
Managing users in auth0-deploy-cli?

### ISSUE THREAD

**Issue by ncknuna** [auth0/auth0-deploy-cli#96]
Hey folks, first of all, thanks for developing this tool! 

Is there a chance we could get support for managing users here as well? I'm working in the enterprise space where we have a very limited number of users and manage their accounts ourselves, and it'd be nice to manage that in config

**Comment by stevezau** [comment]
@fyockm what's your thoughts on this?

I will be looking to add support for roles but i don't think users makes sense as it's not really tenant config.

**Comment by fyockm** [comment]
@stevezau I have to agree. User management seems to be out of the scope of the deploy cli.

The intention of the deploy CLI is to manage the resources of the identity platform, while Users are part of the data that flows through the platform. It seems like there would be a mixing of concerns if User Management was included.

@ncknuna I'll add your request as feedback for potential enhancements.
I would also recommend taking a look at the [Auth0 Import/Export Extension](https://auth0.com/docs/extensions/user-import-export) and underlying APIs.

**Comment by ncknuna** [comment]
Yup, totally makes sense, I just figured it wouldn't hurt to ask :)
