### ISSUE TITLE
emailProvider show sensitive data in logs during import

### ISSUE THREAD

**Issue by johankvint** [auth0/auth0-deploy-cli#97]
Hi,

I'm trying out this cli and when adding an emailProvider during import, `smtp_username` and `smtp_pass` show up in cleartext in logs. 
I think those should not be displayed at all or obfuscated.

```
2019-02-28T08:43:33.809Z - info: Updated [emailProvider]: {"name":"smtp","enabled":true,"credentials":{"smtp_host":"xxxxxxxx","smtp_port":123,"smtp_user":"xxxxxxxx","smtp_pass":"xxxxxxxx"}}
```

**Comment by stevezau** [comment]
Thanks for reporting, some bug fixes were pushed to emailProvider recently. 

should be fixed when https://github.com/auth0-extensions/auth0-source-control-extension-tools/pull/62 is merged

**Comment by woohgit** [comment]
@stevezau Any updates on this?
