### ISSUE TITLE
Cannot import in YAML format with duplicate client names

### ISSUE THREAD

**Issue by ArtiomCiumac** [auth0/auth0-deploy-cli#98]
If a tenant contains multiple clients with the same name - they cannot be imported back. The import fails with the following log messages:
```
2019-03-01T16:06:12.988Z - error: Problem running command import during stage validate when processing type clients
2019-03-01T16:06:12.989Z - error: There are multiple clients with the same name combinations
      [["My App","My App"]].
       Names must be unique.
```

Steps to reproduce:
1. In any tenant create two clients with the same name, for example the default "My App".
2. Export the tenant configuration in yaml format by running something like:
     `a0deploy export -c config.json -f yaml -o tenant-folder`
3. Delete the two created clients in the tenant management dashboard.
4. Import the tenant configuration back by running something like:
    `a0deploy import -c config.json -i tenant-folder/tenant.yaml`

Actual results:
The command fails with the error mentioned above.

Expected results:
The command should succeed and the deleted clients should be recreated.

**Comment by zxan1285** [comment]
Deploy-CLI is using name as an identifier, because ids cannot be imported. So the name must be unique. It's by design and won't be changed.
